export type NetappSdkFunctions =
  'action-test-key-optionality-defaultaction' |
  'active-directory-account-get-iter' |
  'aggr-add' |
  'aggr-autobalance-aggregate-state-get-iter' |
  'aggr-autobalance-config-get' |
  'aggr-autobalance-config-modify' |
  'aggr-autobalance-notification-get-iter' |
  'aggr-autobalance-volume-state-get-iter' |
  'aggr-check-spare-low' |
  'aggr-cluster-space-details-get' |
  'aggr-create' |
  'aggr-destroy' |
  'aggr-efficiency-cumulated-get' |
  'aggr-efficiency-get-iter' |
  'aggr-get-filer-info' |
  'aggr-get-iter' |
  'aggr-mirror' |
  'aggr-modify-raid-type' |
  'aggr-object-store-attach' |
  'aggr-object-store-config-create' |
  'aggr-object-store-config-delete' |
  'aggr-object-store-config-get' |
  'aggr-object-store-config-get-iter' |
  'aggr-object-store-config-modify' |
  'aggr-object-store-config-provider-list' |
  'aggr-object-store-get-iter' |
  'aggr-object-store-modify' |
  'aggr-object-store-storage-aggregate-object-store-replace' |
  'aggr-object-store-storage-aggregate-object-store-upgrade-name-format' |
  'aggr-object-store-tiering-get' |
  'aggr-object-store-tiering-modify' |
  'aggr-object-store-vol-btuuids-get-iter' |
  'aggr-offline' |
  'aggr-online' |
  'aggr-options-list-info' |
  'aggr-recommendation-assign-disks' |
  'aggr-recommendation-configure' |
  'aggr-recommendation-configure-progress-get' |
  'aggr-recommendation-configure-start' |
  'aggr-recommendation-create' |
  'aggr-recommendation-details-get' |
  'aggr-recommendation-get' |
  'aggr-recommendation-verify' |
  'aggr-relocation' |
  'aggr-relocation-status' |
  'aggr-remove-stale-record' |
  'aggr-rename' |
  'aggr-restrict' |
  'aggr-resync-options-get' |
  'aggr-resync-options-get-iter' |
  'aggr-resync-options-set' |
  'aggr-scrub-list-info' |
  'aggr-scrub-resume' |
  'aggr-scrub-start' |
  'aggr-scrub-stop' |
  'aggr-scrub-suspend' |
  'aggr-set-option' |
  'aggr-space-get-iter' |
  'aggr-spare-get-iter' |
  'aggr-spare-requirements-get-iter' |
  'aggr-status-get-iter' |
  'aggr-verify-list-info' |
  'aggr-verify-resume' |
  'aggr-verify-start' |
  'aggr-verify-stop' |
  'aggr-verify-suspend' |
  'alternate-destroy-iter-1' |
  'alternate-destroy-iter-1-inout' |
  'alternate-get-1' |
  'alternate-get-1-inout' |
  'alternate-get-iter-1' |
  'alternate-get-iter-1-inout' |
  'alternate-get-iter-2' |
  'alternate-get-iter-2-inout' |
  'alternate-modify-iter' |
  'alternate-modify-iter-inout' |
  'antivirus-modify' |
  'application-cluster-supported' |
  'application-details-get-iter' |
  'application-get-iter' |
  'application-lun-get-iter' |
  'application-provisioning-aggr-get-iter' |
  'application-provisioning-config-get' |
  'application-provisioning-config-modify' |
  'application-provisioning-job-get-iter' |
  'application-provisioning-lun-results-get' |
  'application-provisioning-set-version' |
  'application-provisioning-volume-get-iter' |
  'application-provisioning-volume-results-get' |
  'application-snapshot-get-iter' |
  'application-stats-get-iter' |
  'application-supported-aggr-by-restraint-get-iter' |
  'application-template-get-iter' |
  'application-volume-get-iter' |
  'application-vserver-supported-get-iter' |
  'audit-log-config-get' |
  'audit-log-config-modify' |
  'audit-log-get' |
  'audit-log-get-iter' |
  'autogenzapi-create' |
  'autogenzapi-destroy' |
  'autogenzapi-get-iter' |
  'autogenzapi-modify' |
  'autogenzapi2-get-iter' |
  'autogenzapi3-create' |
  'autogenzapi3-destroy' |
  'autogenzapi3-get-iter' |
  'autogenzapi3-method1' |
  'autogenzapi3-modify' |
  'autogenzapiaction-dummy-autozapi-action-cmd' |
  'autosupport-budget-get' |
  'autosupport-budget-get-iter' |
  'autosupport-budget-get-total-records' |
  'autosupport-budget-modify' |
  'autosupport-check-iter' |
  'autosupport-compliant-get' |
  'autosupport-compliant-get-iter' |
  'autosupport-compliant-get-total-records' |
  'autosupport-config-get' |
  'autosupport-config-get-iter' |
  'autosupport-config-get-total-records' |
  'autosupport-config-modify' |
  'autosupport-destinations-get' |
  'autosupport-destinations-get-iter' |
  'autosupport-destinations-get-total-records' |
  'autosupport-download-get' |
  'autosupport-download-get-iter' |
  'autosupport-history-cancel' |
  'autosupport-history-get' |
  'autosupport-history-get-iter' |
  'autosupport-history-get-total-records' |
  'autosupport-history-retransmit' |
  'autosupport-invoke' |
  'autosupport-invoke-core-upload' |
  'autosupport-invoke-diagnostic' |
  'autosupport-invoke-diagnostic-iter' |
  'autosupport-invoke-iter' |
  'autosupport-invoke-performance-archive' |
  'autosupport-invoke-performance-archive-iter' |
  'autosupport-invoke-splog' |
  'autosupport-manifest-get-iter' |
  'autosupport-manifest-get-total-records' |
  'autosupport-trigger-get' |
  'autosupport-trigger-get-iter' |
  'autosupport-trigger-get-total-records' |
  'autosupport-trigger-modify' |
  'autozapiview-get-iter' |
  'av-get-engine-info' |
  'av-get-engine-options' |
  'av-get-log' |
  'av-get-remedy-info' |
  'av-get-version-info' |
  'av-log-iter' |
  'av-on-access-policy-get-iter' |
  'av-on-demand-command-abort' |
  'av-on-demand-command-run' |
  'av-on-demand-command-scan-cluster-create' |
  'av-on-demand-command-scan-cluster-delete' |
  'av-on-demand-command-scan-cluster-get' |
  'av-on-demand-command-scan-cluster-get-iter' |
  'av-on-demand-command-scan-cluster-modify' |
  'av-on-demand-command-scan-dir-get-iter' |
  'av-on-demand-command-scan-file-get-iter' |
  'av-on-demand-command-scan-vserver-get-iter' |
  'av-on-demand-command-schedule' |
  'av-on-demand-command-unschedule' |
  'av-on-demand-job-get-iter' |
  'av-on-demand-report-get-iter' |
  'av-on-demand-report-print' |
  'av-on-demand-report-upload' |
  'av-set-engine-info' |
  'av-set-engine-options' |
  'av-set-log' |
  'av-set-remedy-info' |
  'av-set-version-info' |
  'av-start-update' |
  'cache-policy-get' |
  'cache-policy-get-iter' |
  'cache-policy-modify' |
  'cache-policy-modify-iter' |
  'capability-can-be-enabled' |
  'capability-can-be-enabled-shim' |
  'capability-can-boot-shim' |
  'capability-can-join-shim' |
  'capability-check-peers' |
  'capability-disable' |
  'capability-downgrade-commit-shim' |
  'capability-downgrade-prepare-shim' |
  'capability-enable' |
  'capability-get' |
  'capability-get-cluster-set' |
  'capability-get-iter' |
  'capability-is-enabled' |
  'capability-is-enabled-during-downgrade-shim' |
  'capability-is-local-node-enable-ready' |
  'capability-local-cache-evict-local-cache-entry' |
  'capability-local-cache-get-local-cache-entry' |
  'capability-local-cache-get-local-cache-size' |
  'capability-local-cache-put-local-cache-entry' |
  'capability-mark-local-node-enable-ready' |
  'capability-recommend-release-shim' |
  'capability-replicate-manifest-for-join-shim' |
  'capability-software-update-check-shim' |
  'cf-aggregate-giveback-status' |
  'cf-force-takeover' |
  'cf-get-iter' |
  'cf-get-partner' |
  'cf-giveback' |
  'cf-hwassist-stats' |
  'cf-hwassist-stats-clear' |
  'cf-hwassist-status' |
  'cf-hwassist-test' |
  'cf-mode-set' |
  'cf-modify-iter' |
  'cf-service-disable' |
  'cf-service-enable' |
  'cf-status' |
  'cf-takeover' |
  'cf-takeover-status' |
  'cifs-branchcache-get-iter' |
  'cifs-character-mapping-get-iter' |
  'cifs-check-server-get-iter' |
  'cifs-connection-get-iter' |
  'cifs-domain-discovered-servers-get-iter' |
  'cifs-domain-name-mapping-search-get-iter' |
  'cifs-domain-password-schedule-get-iter' |
  'cifs-domain-preferred-dc-get-iter' |
  'cifs-domain-server-discovery-mode-get-iter' |
  'cifs-domain-trusts-get-iter' |
  'cifs-foo-get-iter' |
  'cifs-home-directory-get-iter' |
  'cifs-home-directory-search-path-get-iter' |
  'cifs-local-group-get-iter' |
  'cifs-local-group-members-get-iter' |
  'cifs-local-user-get-iter' |
  'cifs-local-user-membership-get-iter' |
  'cifs-nbtstat-get-iter' |
  'cifs-options-get-iter' |
  'cifs-preferred-dc-check-get-iter' |
  'cifs-privilege-get-iter' |
  'cifs-security-get-iter' |
  'cifs-server-get-iter' |
  'cifs-session-close' |
  'cifs-session-file-close' |
  'cifs-session-file-get-iter' |
  'cifs-session-get-iter' |
  'cifs-shadowcopy-add-files' |
  'cifs-shadowcopy-ems-get-iter' |
  'cifs-shadowcopy-keep-snapshot' |
  'cifs-shadowcopy-restore-dir' |
  'cifs-share-access-control-get-iter' |
  'cifs-share-get-iter' |
  'cifs-symlink-get-iter' |
  'cifs-user-home-directory-path-get-iter' |
  'cifs-users-and-group-local-group-members-get-iter' |
  'cifs-users-and-group-local-user-membership-get-iter' |
  'cifs-users-and-groups-delete-cifs-lug' |
  'clock-get-clock' |
  'clock-get-timezone' |
  'clone-deletion-get-iter' |
  'clone-split-load-get-iter' |
  'clone-split-load-modify' |
  'clone-token-create' |
  'clone-token-delete' |
  'clone-token-get' |
  'clone-token-get-iter' |
  'clone-token-modify-expiry-limit' |
  'cluster-add-node' |
  'cluster-add-node-status-get-iter' |
  'cluster-application-record-create' |
  'cluster-application-record-delete' |
  'cluster-application-record-delete-iter' |
  'cluster-application-record-get-iter' |
  'cluster-application-record-modify' |
  'cluster-application-record-modify-iter' |
  'cluster-contact-get' |
  'cluster-contact-modify' |
  'cluster-create' |
  'cluster-create-join-progress-get' |
  'cluster-ha-get' |
  'cluster-ha-modify' |
  'cluster-identity-get' |
  'cluster-identity-modify' |
  'cluster-image-get' |
  'cluster-image-get-download-progress' |
  'cluster-image-get-iter' |
  'cluster-image-get-upgrade-plan' |
  'cluster-image-metrocluster-update-progress-info-get' |
  'cluster-image-node-update-progress-info' |
  'cluster-image-package-delete' |
  'cluster-image-package-download' |
  'cluster-image-package-download-abort' |
  'cluster-image-package-local-get' |
  'cluster-image-package-local-get-iter' |
  'cluster-image-update' |
  'cluster-image-update-cancel' |
  'cluster-image-update-history-get-iter' |
  'cluster-image-update-log-get-iter' |
  'cluster-image-update-pause' |
  'cluster-image-update-progress-get-iter' |
  'cluster-image-update-progress-info' |
  'cluster-image-update-resume' |
  'cluster-image-validate' |
  'cluster-join' |
  'cluster-log-forward-create' |
  'cluster-log-forward-destroy' |
  'cluster-log-forward-get' |
  'cluster-log-forward-get-iter' |
  'cluster-log-forward-modify' |
  'cluster-log-forward-statistics-get' |
  'cluster-log-forward-statistics-get-iter' |
  'cluster-node-get' |
  'cluster-node-get-iter' |
  'cluster-node-modify' |
  'cluster-peer-active-address-insert' |
  'cluster-peer-active-addresses-get' |
  'cluster-peer-active-addresses-register' |
  'cluster-peer-authn-offer-cancel' |
  'cluster-peer-authn-offer-get' |
  'cluster-peer-authn-offer-get-iter' |
  'cluster-peer-authn-offer-modify' |
  'cluster-peer-connection-destroy' |
  'cluster-peer-connections-get' |
  'cluster-peer-connections-get-iter' |
  'cluster-peer-create' |
  'cluster-peer-delete' |
  'cluster-peer-get' |
  'cluster-peer-get-iter' |
  'cluster-peer-health-info-get' |
  'cluster-peer-health-info-get-iter' |
  'cluster-peer-modify' |
  'cluster-peer-modify-local-name' |
  'cluster-peer-ping-cluster-peer-test-check-mtu' |
  'cluster-peer-ping-iter' |
  'cluster-peer-policy-get' |
  'cluster-peer-policy-modify' |
  'cluster-peer-stable-addresses-get' |
  'cluster-peer-stable-addresses-register' |
  'cluster-remove-node' |
  'cluster-swt-get-iter' |
  'cluster-unjoin' |
  'cluster-zoneinfo-get' |
  'cluster-zoneinfo-load-from-uri' |
  'config-backup-copy' |
  'config-backup-create' |
  'config-backup-delete' |
  'config-backup-download' |
  'config-backup-info-get' |
  'config-backup-info-get-iter' |
  'config-backup-rename' |
  'config-backup-settings-get' |
  'config-backup-settings-modify' |
  'config-backup-settings-password-set' |
  'config-backup-upload' |
  'controller-replacement-cancel' |
  'controller-replacement-get-progress' |
  'controller-replacement-pause' |
  'controller-replacement-resume' |
  'controller-replacement-start' |
  'core-segment-delete-all' |
  'core-segment-destroy' |
  'core-segment-get' |
  'core-segment-get-iter' |
  'coredump-config-get' |
  'coredump-config-get-iter' |
  'coredump-config-get-total-records' |
  'coredump-config-modify' |
  'coredump-config-modify-iter' |
  'coredump-delete-all' |
  'coredump-delete-core' |
  'coredump-delete-core-iter' |
  'coredump-get' |
  'coredump-get-iter' |
  'coredump-get-total-records' |
  'coredump-save-all' |
  'coredump-save-core' |
  'coredump-save-core-iter' |
  'coredump-trigger' |
  'coredump-upload-core' |
  'cost-center-statistics-get' |
  'cost-center-statistics-get-iter' |
  'cost-center-statistics-get-total-records' |
  'dashboard-alarm-get' |
  'dashboard-alarm-get-iter' |
  'dashboard-alarm-get-total-records' |
  'dashboard-alarm-threshold-get' |
  'dashboard-alarm-threshold-get-iter' |
  'dashboard-alarm-threshold-get-total-records' |
  'dashboard-alarm-threshold-modify' |
  'data-lif-capacity' |
  'data-lif-capacity-details' |
  'default-destroy-iter' |
  'default-destroy-iter-inout' |
  'default-get' |
  'default-get-inout' |
  'default-get-iter' |
  'default-get-iter-inout' |
  'default-modify-iter' |
  'default-modify-iter-inout' |
  'diagnosis-alert-definition-get' |
  'diagnosis-alert-definition-get-iter' |
  'diagnosis-alert-get' |
  'diagnosis-alert-get-iter' |
  'diagnosis-alert-modify' |
  'diagnosis-config-get' |
  'diagnosis-config-get-iter' |
  'diagnosis-delete-alert' |
  'diagnosis-policy-definition-get' |
  'diagnosis-policy-definition-get-iter' |
  'diagnosis-policy-modify' |
  'diagnosis-status-get' |
  'diagnosis-subscriptions-create' |
  'diagnosis-subscriptions-get' |
  'diagnosis-subscriptions-get-iter' |
  'diagnosis-subscriptions-modify' |
  'diagnosis-subsystem-config-get' |
  'diagnosis-subsystem-config-get-iter' |
  'diagnosis-subsystem-config-modify' |
  'disk-check-autopartition-state' |
  'disk-encrypt-get' |
  'disk-encrypt-get-iter' |
  'disk-encrypt-modify' |
  'disk-encrypt-modify-iter' |
  'disk-encrypt-sanitize' |
  'disk-encrypt-sanitize-iter' |
  'disk-encrypt-status-get' |
  'disk-encrypt-status-get-iter' |
  'disk-fail' |
  'disk-remove' |
  'disk-replace-start' |
  'disk-replace-stop' |
  'disk-sanown-assign' |
  'disk-sanown-filer-list-info' |
  'disk-sanown-list-info' |
  'disk-sanown-reassign' |
  'disk-sanown-remove-ownership' |
  'disk-unfail' |
  'disk-update-disk-fw' |
  'disk-zero-spares' |
  'dummy-addquery-alt-get' |
  'dummy-addquery-create' |
  'dummy-addquery-get-iter' |
  'dummy-addquery-modify' |
  'dummy-async-volume-create' |
  'dummy-async-volume-create-args' |
  'dummy-av-get-engine-options' |
  'dummy-av-set-engine-options' |
  'dummy-fcp-create' |
  'dummy-fcp-destroy' |
  'dummy-fcp-get-iter' |
  'dummy-file-dummy-read-file' |
  'dummy-listInfo-only-get' |
  'dummy-listInfo-only-list-info' |
  'dummy-quota-create' |
  'dummy-quota-destroy' |
  'dummy-quota-report' |
  'dummy-quota-report-no-input' |
  'dummy-storage-initiator-errors-list-info' |
  'dummy-storage-initiator-errors-list-info-alt' |
  'dummy-storage-initiator-errors-list-info-empty' |
  'dummy-vserver-destroy-iter' |
  'dummy-vserver-dosomething' |
  'dummy-vserver-family-test-alt-create' |
  'dummy-vserver-family-test-alt-destroy' |
  'dummy-vserver-family-test-alt-get' |
  'dummy-vserver-family-test-alt-list-info' |
  'dummy-vserver-family-test-alt-modify' |
  'dummy-vserver-family-test-destroy-iter' |
  'dummy-vserver-family-test-get-iter' |
  'dummy-vserver-family-test-list-info' |
  'dummy-vserver-family-test-modify-iter' |
  'dummy-vserver-fcp-list-get-iter' |
  'dummy-vserver-file-dummy-vserver-read-file-alt' |
  'dummy-vserver-get-iter' |
  'dummy-vserver-list-info' |
  'dummy-vserver-list-info-1-alt' |
  'dummy-vserver-list-info-2-alt' |
  'dummy-vserver-list-info-3-alt' |
  'dummy-vserver-list-info-alt' |
  'dummy-vserver-modify-iter' |
  'dummy-zapi-delete-async' |
  'dummy-zapi-delete-async-nowait' |
  'dummy-zapi-delete-async-nowait-returnsok' |
  'dummy-zapi-jobid-async' |
  'dummy-zapi-jobid-async-nowait' |
  'dummy-zapi-key-attribute-specified-type' |
  'dummylun-create' |
  'dummylun-create-by-size' |
  'dummylun-create-by-size-alt' |
  'dummylun-destroy-iter' |
  'dummylun-get-alt' |
  'dummylun-get-iter' |
  'dummylun-get-iter-alt' |
  'dummylun-list-info' |
  'dummylun-list-info-alt' |
  'dummylun-list-info-alt1' |
  'dummylun-list-info-alt2' |
  'ems-config-get' |
  'ems-config-modify' |
  'ems-config-set-proxy-password' |
  'ems-destination-create' |
  'ems-destination-destroy' |
  'ems-destination-destroy-iter' |
  'ems-destination-get' |
  'ems-destination-get-iter' |
  'ems-destination-modify' |
  'ems-destination-modify-iter' |
  'ems-event-catalog-get-iter' |
  'ems-event-filter-copy' |
  'ems-event-filter-create' |
  'ems-event-filter-destroy-iter' |
  'ems-event-filter-get-iter' |
  'ems-event-filter-rename' |
  'ems-event-filter-rule-add' |
  'ems-event-filter-rule-delete' |
  'ems-event-filter-rule-reorder' |
  'ems-event-filter-test' |
  'ems-event-notification-create' |
  'ems-event-notification-destination-check' |
  'ems-event-notification-destination-create' |
  'ems-event-notification-destination-destroy-iter' |
  'ems-event-notification-destination-get-iter' |
  'ems-event-notification-destination-modify-iter' |
  'ems-event-notification-destroy-iter' |
  'ems-event-notification-get-iter' |
  'ems-event-notification-history-get-iter' |
  'ems-event-notification-modify-iter' |
  'ems-mail-history-destroy' |
  'ems-mail-history-destroy-iter' |
  'ems-mail-history-get' |
  'ems-mail-history-get-iter' |
  'ems-message-get' |
  'ems-message-get-iter' |
  'ems-routing-add-destination' |
  'ems-routing-get' |
  'ems-routing-get-iter' |
  'ems-routing-modify' |
  'ems-routing-modify-iter' |
  'ems-routing-remove-destination' |
  'ems-snmp-history-destroy' |
  'ems-snmp-history-destroy-iter' |
  'ems-snmp-history-get' |
  'ems-snmp-history-get-iter' |
  'ems-status-get' |
  'ems-status-get-iter' |
  'environment-sensors-get-iter' |
  'event-log-get-iter' |
  'export-check-access-get-iter' |
  'export-policy-get-iter' |
  'export-rule-get-create-defaults' |
  'export-rule-get-iter' |
  'export-rule-test-revert' |
  'exports-access-cache-all-vservers-get' |
  'exports-access-cache-all-vservers-modify' |
  'exports-access-cache-config-get-iter' |
  'external-cache-dumplog' |
  'external-cache-get' |
  'external-cache-modify' |
  'external-cache-reconstruct' |
  'external-cache-reset' |
  'external-cache-snapshot' |
  'fc-config-adapter-disable' |
  'fc-config-adapter-enable' |
  'fc-config-list-info' |
  'fc-config-set-adapter-fc-type' |
  'fcp-adapter-config-down' |
  'fcp-adapter-config-up' |
  'fcp-adapter-dump' |
  'fcp-adapter-get-iter' |
  'fcp-adapter-reset' |
  'fcp-adapter-set-speed' |
  'fcp-adapter-stats-get-iter' |
  'fcp-initiator-get-iter' |
  'fcp-interface-get-iter' |
  'fcp-nameserver-get-iter' |
  'fcp-ping-igroup-view-get-iter' |
  'fcp-ping-initiator-get-iter' |
  'fcp-port-name-get-iter' |
  'fcp-service-get-iter' |
  'fcp-topology-get-iter' |
  'fcp-topology-port-get-iter' |
  'fcp-wwpnalias-get-iter' |
  'fcp-zone-get-iter' |
  'fcport-get-link-state' |
  'feature-status-list-info' |
  'feature-usage-get-iter' |
  'feature-usage-summary-get-iter' |
  'file-assign-qos' |
  'file-compact-data' |
  'file-copy-destroy' |
  'file-copy-get-iter' |
  'file-copy-start' |
  'file-directory-security-ntfs-dacl-get-iter' |
  'file-directory-security-ntfs-get-iter' |
  'file-directory-security-ntfs-sacl-get-iter' |
  'file-directory-security-policy-get-iter' |
  'file-directory-security-policy-task-get-iter' |
  'file-fingerprint-abort' |
  'file-fingerprint-dump' |
  'file-fingerprint-get-iter' |
  'file-move-destroy' |
  'file-move-get-iter' |
  'file-move-start' |
  'fileservice-audit-config-get-iter' |
  'fileservice-audit-config-get-total-records' |
  'flash-device-get-iter' |
  'flash-device-list-info' |
  'flash-get-thresholds' |
  'flash-thresholds-get-iter' |
  'flexcache-connected-cache-get-iter' |
  'flexcache-get-iter' |
  'flexcache-origin-config-get-iter' |
  'flexcache-usage-get' |
  'fpolicy-passthrough-read-connection-get-iter' |
  'fpolicy-policy-event-get-iter' |
  'fpolicy-policy-external-engine-get-iter' |
  'fpolicy-policy-get-iter' |
  'fpolicy-policy-scope-get-iter' |
  'fpolicy-policy-status-get-iter' |
  'fpolicy-server-status-get-iter' |
  'gpo-applied-info-get-iter' |
  'gpo-get-iter' |
  'gpo-gpresult-info-get-iter' |
  'gpo-restricted-group-applied-info-get-iter' |
  'gpo-restricted-group-defined-info-get-iter' |
  'group-mapping-get-iter' |
  'ha-interconnect-channel-info-get-iter' |
  'ha-interconnect-clear-error-statistics' |
  'ha-interconnect-clear-port-counters' |
  'ha-interconnect-clear-port-symbol-errors' |
  'ha-interconnect-completion-queue-statistics-get-iter' |
  'ha-interconnect-config-details-get-iter' |
  'ha-interconnect-confirm-delivery-statistics-get-iter' |
  'ha-interconnect-connection-status-get-iter' |
  'ha-interconnect-flint-flash-details-get-iter' |
  'ha-interconnect-flint-image-details-get-iter' |
  'ha-interconnect-flint-verify-flash' |
  'ha-interconnect-flint-verify-image' |
  'ha-interconnect-flush-details-get-iter' |
  'ha-interconnect-get-channel-info' |
  'ha-interconnect-get-completion-queue-statistics' |
  'ha-interconnect-get-config-details' |
  'ha-interconnect-get-confirm-delivery-statistics' |
  'ha-interconnect-get-connection-status' |
  'ha-interconnect-get-flint-flash-details' |
  'ha-interconnect-get-flint-image-details' |
  'ha-interconnect-get-flush-details' |
  'ha-interconnect-get-nvram-configuration' |
  'ha-interconnect-get-ood-status' |
  'ha-interconnect-get-performance-statistics' |
  'ha-interconnect-get-port-details' |
  'ha-interconnect-get-scatter-gather-list-statistics' |
  'ha-interconnect-get-timeout-values' |
  'ha-interconnect-get-viif-channel-memory-statistics' |
  'ha-interconnect-link-off' |
  'ha-interconnect-link-on' |
  'ha-interconnect-modify-timeout-values' |
  'ha-interconnect-nic-reset' |
  'ha-interconnect-nvram-configuration-get-iter' |
  'ha-interconnect-ood-clear-error-statistics' |
  'ha-interconnect-ood-clear-performance-statistics' |
  'ha-interconnect-ood-disable-statistics' |
  'ha-interconnect-ood-enable-statistics' |
  'ha-interconnect-ood-optimization-off' |
  'ha-interconnect-ood-optimization-on' |
  'ha-interconnect-ood-send-diagnostic-buffer' |
  'ha-interconnect-ood-status-get-iter' |
  'ha-interconnect-performance-statistics-get-iter' |
  'ha-interconnect-port-details-get-iter' |
  'ha-interconnect-scatter-gather-list-statistics-get-iter' |
  'ha-interconnect-timeout-values-get-iter' |
  'ha-interconnect-viif-channel-memory-statistics-get-iter' |
  'haosc-lookup' |
  'igroup-disable-aix-support' |
  'igroup-get-iter' |
  'igroup-os-type-list' |
  'iscsi-connection-get-iter' |
  'iscsi-initiator-auth-get-iter' |
  'iscsi-initiator-get-iter' |
  'iscsi-interface-accesslist-get-iter' |
  'iscsi-interface-get-iter' |
  'iscsi-isns-get-iter' |
  'iscsi-service-get-iter' |
  'iscsi-session-get-iter' |
  'iscsi-stats-get-iter' |
  'iscsi-tpgroup-get-iter' |
  'job-bad-erase' |
  'job-bad-get-iter' |
  'job-by-node-get-iter' |
  'job-completed-get-iter' |
  'job-delete-iter' |
  'job-expunge-iter' |
  'job-get-iter' |
  'job-history-get-iter' |
  'job-init-state-get' |
  'job-init-state-get-iter' |
  'job-kick' |
  'job-pause-iter' |
  'job-private-completed-get-iter' |
  'job-private-delete-iter' |
  'job-private-get-iter' |
  'job-private-pause-iter' |
  'job-private-resume-iter' |
  'job-private-soft-pause-iter' |
  'job-private-stop-iter' |
  'job-queue-get' |
  'job-queue-get-iter' |
  'job-resume-iter' |
  'job-schedule-consumer-get' |
  'job-schedule-consumer-get-iter' |
  'job-schedule-cron-create' |
  'job-schedule-cron-destroy' |
  'job-schedule-cron-destroy-iter' |
  'job-schedule-cron-get' |
  'job-schedule-cron-get-iter' |
  'job-schedule-cron-modify' |
  'job-schedule-get' |
  'job-schedule-get-iter' |
  'job-schedule-interval-create' |
  'job-schedule-interval-destroy' |
  'job-schedule-interval-destroy-iter' |
  'job-schedule-interval-get' |
  'job-schedule-interval-get-iter' |
  'job-schedule-interval-modify' |
  'job-soft-pause-iter' |
  'job-stop-iter' |
  'job-type-by-category-get' |
  'job-type-by-category-get-iter' |
  'job-type-get' |
  'job-type-get-iter' |
  'job-unclaim-iter' |
  'kerberos-config-get-iter' |
  'kerberos-realm-get-iter' |
  'ldap-check-get-iter' |
  'ldap-client-get-iter' |
  'ldap-client-schema-get-iter' |
  'ldap-config-get-iter' |
  'license-v2-add' |
  'license-v2-apply' |
  'license-v2-capacity-create' |
  'license-v2-capacity-get-iter' |
  'license-v2-cleanup-list-info' |
  'license-v2-delete' |
  'license-v2-delete-expired' |
  'license-v2-delete-unused' |
  'license-v2-entitlement-risk-get-iter' |
  'license-v2-leases-update' |
  'license-v2-license-manager-config-get' |
  'license-v2-license-manager-config-modify' |
  'license-v2-license-manager-status-get-iter' |
  'license-v2-list-info' |
  'license-v2-promote' |
  'license-v2-status-get-iter' |
  'license-v2-status-list-info' |
  'license-v2-subscription-create' |
  'license-v2-subscription-get-iter' |
  'location-led-get' |
  'location-led-modify' |
  'lock-break-iter' |
  'lock-get-iter' |
  'lun-alignment-get-iter' |
  'lun-bind-get-iter' |
  'lun-copy-cancel' |
  'lun-copy-get-iter' |
  'lun-copy-modify' |
  'lun-copy-pause' |
  'lun-copy-resume' |
  'lun-copy-start' |
  'lun-debug-get' |
  'lun-generate-serial' |
  'lun-get-iter' |
  'lun-get-vdisk-attributes' |
  'lun-group-internal-rebuild' |
  'lun-import-create' |
  'lun-import-delete' |
  'lun-import-get-iter' |
  'lun-import-pause' |
  'lun-import-resume' |
  'lun-import-start' |
  'lun-import-stop' |
  'lun-import-throttle' |
  'lun-import-verify-start' |
  'lun-import-verify-stop' |
  'lun-initiator-list-map-info' |
  'lun-map-get-iter' |
  'lun-move-get-iter' |
  'lun-os-type-list' |
  'lun-prepare-to-downgrade' |
  'lun-stats-get-iter' |
  'lun-test-vdisk-size' |
  'lun-transition-7mode-destroy' |
  'lun-transition-7mode-get-iter' |
  'lun-transition-start' |
  'lun-transition-volume-get-iter' |
  'memoryperf-run' |
  'method-for-key-optionality-default' |
  'metrocluster-add-disks' |
  'metrocluster-check-aggregate-eligibility-get' |
  'metrocluster-check-aggregate-eligibility-get-iter' |
  'metrocluster-check-aggregate-get-iter' |
  'metrocluster-check-capture-status-get' |
  'metrocluster-check-cluster-get-iter' |
  'metrocluster-check-config-replication-get' |
  'metrocluster-check-connection-get-iter' |
  'metrocluster-check-get-iter' |
  'metrocluster-check-lif-repair-placement' |
  'metrocluster-check-lif-update-vserver-name' |
  'metrocluster-check-node-get-iter' |
  'metrocluster-check-run' |
  'metrocluster-config-diff-get' |
  'metrocluster-config-diff-get-iter' |
  'metrocluster-config-replication-cluster-storage-configuration-get' |
  'metrocluster-config-replication-cluster-storage-configuration-modify' |
  'metrocluster-config-replication-resync-status-get' |
  'metrocluster-configuration-settings-get-iter' |
  'metrocluster-configure' |
  'metrocluster-connection-check' |
  'metrocluster-connection-connect-async' |
  'metrocluster-connection-disconnect-async' |
  'metrocluster-connection-get-iter' |
  'metrocluster-create-periodic-job' |
  'metrocluster-delete-periodic-job' |
  'metrocluster-disable' |
  'metrocluster-disable-periodic-check' |
  'metrocluster-dr-group-create' |
  'metrocluster-dr-group-delete' |
  'metrocluster-dr-group-get-iter' |
  'metrocluster-enable-periodic-check' |
  'metrocluster-get' |
  'metrocluster-heal' |
  'metrocluster-interconnect-adapter-auto-reset-on-error-modify' |
  'metrocluster-interconnect-adapter-get-iter' |
  'metrocluster-interconnect-adapter-modify' |
  'metrocluster-interconnect-adapter-reset' |
  'metrocluster-interconnect-ipfo-get-iter' |
  'metrocluster-interconnect-mirror-get-iter' |
  'metrocluster-interconnect-mirror-modify' |
  'metrocluster-interconnect-mirror-multipath-get-iter' |
  'metrocluster-interface-create' |
  'metrocluster-interface-delete' |
  'metrocluster-interface-get-iter' |
  'metrocluster-interface-modify' |
  'metrocluster-is-configured' |
  'metrocluster-node-get-iter' |
  'metrocluster-operation-get-iter' |
  'metrocluster-operation-statistics-get-iter' |
  'metrocluster-progress-table-get-iter' |
  'metrocluster-show-lif-placement-failures-get-iter' |
  'metrocluster-switchback' |
  'metrocluster-switchover' |
  'metrocluster-tracelog-dump' |
  'metrocluster-unconfigure' |
  'metrocluster-vserver-get-iter' |
  'metrocluster-vserver-resync' |
  'name-mapping-get-iter' |
  'name-mapping-unix-group-get-iter' |
  'name-mapping-unix-user-get-iter' |
  'name-service-nis-binding-detail-get-iter' |
  'name-service-nis-show-bound-iter' |
  'name-service-unix-group-limits-get' |
  'name-service-unix-user-limits-get' |
  'nameservice-get-hostname-from-ipv4' |
  'nameservice-get-ip-from-hostname' |
  'nameservice-get-ipv4-from-hostname' |
  'nameservice-nsswitch-get-iter' |
  'ndmp-node-attributes-get-iter' |
  'ndmp-node-attributes-modify' |
  'ndmp-node-modify-password' |
  'ndmp-node-scope-mode-enable' |
  'ndmp-node-scope-mode-status' |
  'ndmp-node-service-disable' |
  'ndmp-node-service-enable' |
  'ndmp-node-session-info-get-iter' |
  'ndmp-node-session-kill' |
  'ndmp-node-session-kill-all' |
  'ndmp-vserver-attributes-get-iter' |
  'ndmp-vserver-aware-mode-enable' |
  'ndmp-vserver-aware-mode-status' |
  'ndmp-vserver-session-info-get-iter' |
  'net-active-routes-get-iter' |
  'net-arp-active-entry-destroy' |
  'net-arp-active-entry-get' |
  'net-arp-active-entry-get-iter' |
  'net-arp-create' |
  'net-arp-destroy' |
  'net-arp-get' |
  'net-arp-get-iter' |
  'net-bgp-config-create' |
  'net-bgp-config-destroy' |
  'net-bgp-config-get' |
  'net-bgp-config-get-iter' |
  'net-bgp-config-modify' |
  'net-bgp-defaults-get' |
  'net-bgp-defaults-modify' |
  'net-bgp-peer-group-create' |
  'net-bgp-peer-group-destroy' |
  'net-bgp-peer-group-get' |
  'net-bgp-peer-group-get-iter' |
  'net-bgp-peer-group-modify' |
  'net-bgp-peer-group-rename' |
  'net-bgp-vserver-status-get' |
  'net-bgp-vserver-status-get-iter' |
  'net-check-failover' |
  'net-cluster-ping' |
  'net-cluster-ping6' |
  'net-connections-receive-window-size-get' |
  'net-connections-receive-window-size-get-iter' |
  'net-connections-receive-window-size-modify' |
  'net-ddns-get-iter' |
  'net-device-discovery-get-iter' |
  'net-disable-readonly' |
  'net-displaced-interface-get' |
  'net-displaced-interface-get-iter' |
  'net-displaced-vlans-get' |
  'net-displaced-vlans-get-iter' |
  'net-dns-check-get-iter' |
  'net-dns-get-iter' |
  'net-enable-readonly' |
  'net-external-route-table-create' |
  'net-external-route-table-delete' |
  'net-failover-group-add-targets' |
  'net-failover-group-create' |
  'net-failover-group-destroy' |
  'net-failover-group-get-iter' |
  'net-failover-group-modify' |
  'net-failover-group-remove-targets' |
  'net-failover-group-rename' |
  'net-firewall-config-get' |
  'net-firewall-config-get-iter' |
  'net-firewall-config-modify' |
  'net-firewall-config-modify-iter' |
  'net-firewall-policy-create' |
  'net-firewall-policy-destroy' |
  'net-firewall-policy-get-iter' |
  'net-firewall-policy-modify' |
  'net-hosts-get-iter' |
  'net-interface-create' |
  'net-interface-delete' |
  'net-interface-get-iter' |
  'net-interface-migrate' |
  'net-interface-modify' |
  'net-interface-modify-iter' |
  'net-interface-revert' |
  'net-interface-service-get' |
  'net-interface-service-get-iter' |
  'net-interface-service-policy-add-service' |
  'net-interface-service-policy-clone' |
  'net-interface-service-policy-create' |
  'net-interface-service-policy-destroy' |
  'net-interface-service-policy-entry-get-iter' |
  'net-interface-service-policy-get-iter' |
  'net-interface-service-policy-modify-service' |
  'net-interface-service-policy-remove-service' |
  'net-interface-service-policy-rename' |
  'net-interface-service-policy-restore-defaults' |
  'net-ipspaces-assign-vserver' |
  'net-ipspaces-create' |
  'net-ipspaces-destroy' |
  'net-ipspaces-get' |
  'net-ipspaces-get-iter' |
  'net-ipspaces-rename' |
  'net-ndp-active-neighbor-destroy' |
  'net-ndp-active-neighbor-get' |
  'net-ndp-active-neighbor-get-iter' |
  'net-ndp-default-router-delete-all' |
  'net-ndp-default-router-get' |
  'net-ndp-default-router-get-iter' |
  'net-ndp-neighbor-get-iter' |
  'net-ndp-prefix-delete-all' |
  'net-ndp-prefix-get' |
  'net-ndp-prefix-get-iter' |
  'net-net-displaced-interface-restore-home-node' |
  'net-net-displaced-vlans-restore' |
  'net-options-get' |
  'net-options-hypervisor-uplink-monitoring-get' |
  'net-options-hypervisor-uplink-monitoring-modify' |
  'net-options-modify' |
  'net-placement-cache-delete' |
  'net-placement-cache-get-iter' |
  'net-placement-discover' |
  'net-port-broadcast-domain-add-ports' |
  'net-port-broadcast-domain-create' |
  'net-port-broadcast-domain-destroy' |
  'net-port-broadcast-domain-get' |
  'net-port-broadcast-domain-get-iter' |
  'net-port-broadcast-domain-merge' |
  'net-port-broadcast-domain-modify' |
  'net-port-broadcast-domain-remove-ports' |
  'net-port-broadcast-domain-rename' |
  'net-port-broadcast-domain-split' |
  'net-port-delete' |
  'net-port-get' |
  'net-port-get-iter' |
  'net-port-health-monitor-disable' |
  'net-port-health-monitor-enable' |
  'net-port-health-monitor-get' |
  'net-port-health-monitor-get-iter' |
  'net-port-ifgrp-add-port' |
  'net-port-ifgrp-create' |
  'net-port-ifgrp-destroy' |
  'net-port-ifgrp-get' |
  'net-port-ifgrp-remove-port' |
  'net-port-l2reachability-get' |
  'net-port-l2reachability-get-iter' |
  'net-port-l2reachability-repair' |
  'net-port-l2reachability-scan' |
  'net-port-modify' |
  'net-port-modify-iter' |
  'net-qos-marking-get-iter' |
  'net-qos-marking-modify' |
  'net-routes-get-iter' |
  'net-routes-lifs-get-iter' |
  'net-san-lif-placement-get' |
  'net-subnet-add-ranges' |
  'net-subnet-create' |
  'net-subnet-destroy' |
  'net-subnet-get' |
  'net-subnet-get-iter' |
  'net-subnet-modify' |
  'net-subnet-remove-ranges' |
  'net-subnet-rename' |
  'net-subnets-for-broadcast-domain-get' |
  'net-subnets-for-broadcast-domain-get-iter' |
  'net-test-path' |
  'net-traceroute6' |
  'net-tuning-icmp-get' |
  'net-tuning-icmp-modify' |
  'net-tuning-icmp6-get' |
  'net-tuning-icmp6-modify' |
  'net-tuning-tcp-get' |
  'net-tuning-tcp-modify' |
  'net-vip-port-create' |
  'net-vip-port-destroy' |
  'net-vip-port-get' |
  'net-vip-port-get-iter' |
  'net-vlan-create' |
  'net-vlan-delete' |
  'net-vlan-get' |
  'net-vlan-get-iter' |
  'netgroups-file-delete' |
  'netgroups-file-get' |
  'netgroups-file-get-iter' |
  'nfs-all-flash-optimized-get' |
  'nfs-all-flash-optimized-get-iter' |
  'nfs-service-get-create-defaults' |
  'nfs-service-get-iter' |
  'nis-get-iter' |
  'ntdtest-action-alt-simpleget' |
  'ntdtest-action-alt-simpleget-optional' |
  'ntdtest-action-only-doit' |
  'ntdtest-action-only-doit-async' |
  'ntdtest-action-only-dothat' |
  'ntdtest-action-simpleget' |
  'ntdtest-action-top-level-create' |
  'ntdtest-action-top-level-create-alt' |
  'ntdtest-dnested-get' |
  'ntdtest-dnested-get-iter' |
  'ntdtest-empty-tags-get-1' |
  'ntdtest-empty-tags-get-10' |
  'ntdtest-empty-tags-get-11' |
  'ntdtest-empty-tags-get-12' |
  'ntdtest-empty-tags-get-13' |
  'ntdtest-empty-tags-get-2' |
  'ntdtest-empty-tags-get-3' |
  'ntdtest-empty-tags-get-4' |
  'ntdtest-empty-tags-get-5' |
  'ntdtest-empty-tags-get-6' |
  'ntdtest-empty-tags-get-7' |
  'ntdtest-empty-tags-get-8' |
  'ntdtest-empty-tags-get-9' |
  'ntdtest-extensive-alternate-create-1' |
  'ntdtest-extensive-alternate-create-2' |
  'ntdtest-extensive-alternate-destroy-1' |
  'ntdtest-extensive-alternate-get-1' |
  'ntdtest-extensive-alternate-get-2' |
  'ntdtest-extensive-alternate-modify-1' |
  'ntdtest-extensive-default-create' |
  'ntdtest-extensive-default-destroy' |
  'ntdtest-extensive-default-get' |
  'ntdtest-extensive-default-modify' |
  'ntdtest-extensive-destroy-iter' |
  'ntdtest-extensive-get-iter' |
  'ntdtest-extensive-method1-alternate' |
  'ntdtest-extensive-method1-default' |
  'ntdtest-extensive-method2-alternate' |
  'ntdtest-extensive-method2-default' |
  'ntdtest-extensive-method3-default' |
  'ntdtest-extensive-method4-alt' |
  'ntdtest-extensive-method4-default' |
  'ntdtest-extensive-method5-alternate' |
  'ntdtest-extensive-method6-alternate' |
  'ntdtest-extensive-method6-alternate-1' |
  'ntdtest-extensive-method6-default' |
  'ntdtest-extensive-modify-iter' |
  'ntdtest-folding-create' |
  'ntdtest-folding-deep-arrayof-get-iter' |
  'ntdtest-folding-default-get' |
  'ntdtest-folding-destroy' |
  'ntdtest-folding-get' |
  'ntdtest-folding-get-collapsed-and-arrayof' |
  'ntdtest-folding-get-deep-element' |
  'ntdtest-folding-get-element-no-array' |
  'ntdtest-folding-get-full-list' |
  'ntdtest-folding-get-iter' |
  'ntdtest-folding-get-iter-mixed' |
  'ntdtest-folding-get-multiple-field-list-shallow' |
  'ntdtest-folding-get-multiple-field-list-top' |
  'ntdtest-folding-get-multiple-fields-list-array-and-collapsed' |
  'ntdtest-folding-get-shallow-element' |
  'ntdtest-folding-get-single-field-list' |
  'ntdtest-folding-list-info' |
  'ntdtest-folding-list-info-alt' |
  'ntdtest-folding-list-info-deep-element' |
  'ntdtest-folding-multiple-arrays-create' |
  'ntdtest-folding-multiple-arrays-destroy' |
  'ntdtest-folding-multiple-arrays-get-iter' |
  'ntdtest-get' |
  'ntdtest-get-iter' |
  'ntdtest-iterfrom-alt-create' |
  'ntdtest-iterfrom-alt-destroy' |
  'ntdtest-iterfrom-alt-destroy-iter' |
  'ntdtest-iterfrom-alt-get' |
  'ntdtest-iterfrom-alt-get-iter' |
  'ntdtest-iterfrom-alt-list-info' |
  'ntdtest-iterfrom-alt-modify' |
  'ntdtest-iterfrom-alt-modify-iter' |
  'ntdtest-iterfrom-create' |
  'ntdtest-iterfrom-destroy' |
  'ntdtest-iterfrom-destroy-iter' |
  'ntdtest-iterfrom-dupe-create' |
  'ntdtest-iterfrom-dupe-destroy' |
  'ntdtest-iterfrom-dupe-destroy-iter' |
  'ntdtest-iterfrom-dupe-get' |
  'ntdtest-iterfrom-dupe-get-iter' |
  'ntdtest-iterfrom-dupe-list-info' |
  'ntdtest-iterfrom-dupe-modify' |
  'ntdtest-iterfrom-dupe-modify-iter' |
  'ntdtest-iterfrom-get' |
  'ntdtest-iterfrom-get-iter' |
  'ntdtest-iterfrom-list-info' |
  'ntdtest-iterfrom-modify' |
  'ntdtest-iterfrom-modify-iter' |
  'ntdtest-iternoread-create' |
  'ntdtest-iternoread-destroy' |
  'ntdtest-iternoread-destroy-iter' |
  'ntdtest-iternoread-get' |
  'ntdtest-iternoread-get-alt' |
  'ntdtest-iternoread-get-iter' |
  'ntdtest-iternoread-get-iter-alt' |
  'ntdtest-iternoread-list-info' |
  'ntdtest-iternoread-modify' |
  'ntdtest-iternoread-modify-iter' |
  'ntdtest-iterwants-get' |
  'ntdtest-iterwants-get-iter' |
  'ntdtest-list-non-test-action-default' |
  'ntdtest-list-non-test-method-default' |
  'ntdtest-method-only-default' |
  'ntdtest-method-only-method2' |
  'ntdtest-method-only-method3' |
  'ntdtest-method-only-method3-a' |
  'ntdtest-method-only-method3-async' |
  'ntdtest-method-only-method3-async-a' |
  'ntdtest-method-only-method3-async-iter' |
  'ntdtest-method-only-method3-iter' |
  'ntdtest-multiple-array-get-deep-element' |
  'ntdtest-multiple-array-get-shallow-element' |
  'ntdtest-multiple-arrays-get-iter' |
  'ntdtest-multiple-default-method1-alternate' |
  'ntdtest-multiple-default-method1-default' |
  'ntdtest-multiple-inout-method1-alternate' |
  'ntdtest-multiple-inout-method1-default' |
  'ntdtest-multiple-with-default-create' |
  'ntdtest-multiple-with-inout-create' |
  'ntdtest-nonlist-get' |
  'ntdtest-nonlist-get-iter' |
  'ntdtest-shownoread-default-get' |
  'ntdtest-shownoread-get' |
  'ntdtest-top-level-alt-create' |
  'ntdtest-top-level-alt-get' |
  'ntdtest-top-level-default-create' |
  'ntdtest-top-level-default-destroy' |
  'ntdtest-top-level-default-get' |
  'ntdtest-top-level-default-modify' |
  'ntdtest-top-level-no-inputs-create' |
  'ntdtest-view-alternate-create-1' |
  'ntdtest-view-alternate-create-2' |
  'ntdtest-view-alternate-destroy-1' |
  'ntdtest-view-alternate-get-1' |
  'ntdtest-view-alternate-get-2' |
  'ntdtest-view-alternate-modify-1' |
  'ntdtest-view-default-create' |
  'ntdtest-view-default-destroy' |
  'ntdtest-view-default-get' |
  'ntdtest-view-default-modify' |
  'ntdtest-view-destroy-iter' |
  'ntdtest-view-get-iter' |
  'ntdtest-view-modify-iter' |
  'ntp-server-create' |
  'ntp-server-delete' |
  'ntp-server-get' |
  'ntp-server-get-iter' |
  'ntp-server-key-create' |
  'ntp-server-key-delete' |
  'ntp-server-key-get-iter' |
  'ntp-server-key-modify' |
  'ntp-server-modify' |
  'ntp-server-reset' |
  'ntp-server-security-get' |
  'ntp-server-security-set' |
  'ntp-server-status-get' |
  'ntp-server-status-get-iter' |
  'ntp-server-validate' |
  'nvme-disable-experimental' |
  'nvme-enable-experimental' |
  'nvme-feature-get' |
  'nvme-get-iter' |
  'nvme-interface-get-iter' |
  'nvme-license-grace-period-get' |
  'nvme-namespace-get-iter' |
  'nvme-namespace-os-type-list' |
  'nvme-subsystem-controller-get-iter' |
  'nvme-subsystem-get-iter' |
  'nvme-subsystem-host-get-iter' |
  'nvme-subsystem-map-get-iter' |
  'nvme-subsystem-os-type-list' |
  'nvram-encryption-get' |
  'nvram-encryption-modify' |
  'options-get-iter' |
  'options-modify-iter' |
  'perf-archive-config-get' |
  'perf-archive-config-modify' |
  'perf-archive-datastore-get-iter' |
  'perf-awa-get' |
  'perf-awa-get-iter' |
  'perf-awa-start' |
  'perf-awa-stop' |
  'perf-awa-volume-get' |
  'perf-awa-volume-get-iter' |
  'perf-clean-stale-sample-data' |
  'perf-cleanup-sample-duration' |
  'perf-object-counter-list-info' |
  'perf-object-get-instances' |
  'perf-object-instance-list-info-iter' |
  'perf-object-list-info' |
  'perf-object-start' |
  'perf-object-stop' |
  'perf-preset-create' |
  'perf-preset-delete' |
  'perf-preset-detail-get' |
  'perf-preset-get-iter' |
  'perf-preset-modify' |
  'perf-samples-delete' |
  'perf-samples-get-iter' |
  'platform-cap-get-iter' |
  'portset-get-iter' |
  'protection-type-get-iter' |
  'qos-adaptive-policy-group-create' |
  'qos-adaptive-policy-group-delete' |
  'qos-adaptive-policy-group-delete-iter' |
  'qos-adaptive-policy-group-get' |
  'qos-adaptive-policy-group-get-iter' |
  'qos-adaptive-policy-group-modify' |
  'qos-adaptive-policy-group-modify-iter' |
  'qos-adaptive-policy-group-rename' |
  'qos-policy-group-create' |
  'qos-policy-group-delete' |
  'qos-policy-group-delete-iter' |
  'qos-policy-group-get' |
  'qos-policy-group-get-iter' |
  'qos-policy-group-modify' |
  'qos-policy-group-modify-iter' |
  'qos-policy-group-rename' |
  'qos-settings-read-ahead-create' |
  'qos-settings-read-ahead-destroy' |
  'qos-settings-read-ahead-destroy-iter' |
  'qos-settings-read-ahead-get' |
  'qos-settings-read-ahead-get-iter' |
  'qos-settings-read-ahead-modify' |
  'qos-settings-read-ahead-modify-iter' |
  'qos-test-smf-zapi-error' |
  'qos-workload-delete' |
  'qos-workload-delete-iter' |
  'qos-workload-get' |
  'qos-workload-get-iter' |
  'qos-workload-modify' |
  'qos-workload-modify-iter' |
  'qos-workload-policy-count-get' |
  'qtree-list-iter' |
  'quota-list-entries-iter' |
  'quota-policy-copy' |
  'quota-policy-create' |
  'quota-policy-delete-iter' |
  'quota-policy-get-iter' |
  'quota-policy-rename' |
  'quota-policy-rule-count-get-iter' |
  'quota-report-iter' |
  'quota-status-iter' |
  'raidgroup-get-iter' |
  'secd-auth-get-claim-name' |
  'secd-auth-get-dc-info' |
  'secd-auth-show-ontap-admin-unix-creds-using-uid' |
  'secd-auth-show-ontap-admin-unix-creds-using-unix-user-name' |
  'secd-auth-sid-to-uid' |
  'secd-auth-sid-to-unix-user-name' |
  'secd-auth-translate-gid-to-groupname' |
  'secd-auth-translate-sid-to-win-user-name' |
  'secd-auth-translate-uid-to-username' |
  'secd-auth-translate-unix-group-name-to-gid' |
  'secd-auth-translate-unix-user-name-to-uid' |
  'secd-auth-translate-windows-user-name-to-sid' |
  'secd-auth-uid-to-sid' |
  'secd-connection-timeout-get-iter' |
  'secd-dns-forward-lookup' |
  'secd-dns-srv-lookup' |
  'secd-name-mapping-show' |
  'secd-server-discovery-host' |
  'secd-server-discovery-reset' |
  'secd-server-discovery-site' |
  'secd-server-discovery-test' |
  'security-certificate-ca-issued-get-iter' |
  'security-certificate-create' |
  'security-certificate-delete' |
  'security-certificate-delete-iter' |
  'security-certificate-file-get-iter' |
  'security-certificate-generate-csr' |
  'security-certificate-get-iter' |
  'security-certificate-install' |
  'security-certificate-remove-precluster-cert' |
  'security-certificate-rename' |
  'security-certificate-revoke' |
  'security-certificate-sign' |
  'security-certificate-truststore-clear' |
  'security-certificate-truststore-load' |
  'security-config-get' |
  'security-config-modify' |
  'security-config-ocsp-disable' |
  'security-config-ocsp-enable' |
  'security-config-ocsp-get-iter' |
  'security-ipsec-config-get' |
  'security-ipsec-config-modify' |
  'security-ipsec-policy-create' |
  'security-ipsec-policy-delete' |
  'security-ipsec-policy-get' |
  'security-ipsec-policy-get-iter' |
  'security-ipsec-policy-modify' |
  'security-key-manager-add' |
  'security-key-manager-add-iter' |
  'security-key-manager-backup-get' |
  'security-key-manager-config-get' |
  'security-key-manager-config-modify' |
  'security-key-manager-create-key' |
  'security-key-manager-delete' |
  'security-key-manager-delete-iter' |
  'security-key-manager-delete-keys' |
  'security-key-manager-delete-kmip-config' |
  'security-key-manager-get' |
  'security-key-manager-get-iter' |
  'security-key-manager-key-get-iter' |
  'security-key-manager-query-get' |
  'security-key-manager-query-get-iter' |
  'security-key-manager-query-v2-get' |
  'security-key-manager-query-v2-get-iter' |
  'security-key-manager-restore-get' |
  'security-key-manager-restore-get-iter' |
  'security-key-manager-restore-v2-get' |
  'security-key-manager-restore-v2-get-iter' |
  'security-key-manager-setup' |
  'security-key-manager-update-passphrase' |
  'security-key-manager-volume-encryption-supported' |
  'security-last-login-info' |
  'security-login-create' |
  'security-login-delete' |
  'security-login-delete-iter' |
  'security-login-expire-password' |
  'security-login-expire-password-iter' |
  'security-login-get' |
  'security-login-get-iter' |
  'security-login-lock' |
  'security-login-modify' |
  'security-login-modify-iter' |
  'security-login-modify-password' |
  'security-login-role-config-get' |
  'security-login-role-config-get-iter' |
  'security-login-role-config-modify' |
  'security-login-role-config-modify-iter' |
  'security-login-role-create' |
  'security-login-role-delete' |
  'security-login-role-delete-iter' |
  'security-login-role-get' |
  'security-login-role-get-iter' |
  'security-login-role-modify' |
  'security-login-role-modify-iter' |
  'security-login-unlock' |
  'security-login-whoami' |
  'security-protocol-get' |
  'security-protocol-modify' |
  'security-protocol-ssh-get' |
  'security-protocol-ssh-modify' |
  'security-reset' |
  'security-saml-sp-create-async' |
  'security-saml-sp-destroy' |
  'security-saml-sp-get' |
  'security-saml-sp-modify' |
  'security-saml-sp-repair' |
  'security-saml-sp-status-get-iter' |
  'security-security-login-password-prepare-to-downgrade' |
  'security-session-application-stats-get-iter' |
  'security-session-kill-cli-iter' |
  'security-session-limit-application-create' |
  'security-session-limit-application-delete' |
  'security-session-limit-application-get-iter' |
  'security-session-limit-application-modify' |
  'security-session-limit-create' |
  'security-session-limit-delete' |
  'security-session-limit-get-iter' |
  'security-session-limit-location-create' |
  'security-session-limit-location-delete' |
  'security-session-limit-location-get-iter' |
  'security-session-limit-location-modify' |
  'security-session-limit-modify' |
  'security-session-limit-request-create' |
  'security-session-limit-request-delete' |
  'security-session-limit-request-get-iter' |
  'security-session-limit-request-modify' |
  'security-session-limit-user-create' |
  'security-session-limit-user-delete' |
  'security-session-limit-user-get-iter' |
  'security-session-limit-user-modify' |
  'security-session-limit-vserver-create' |
  'security-session-limit-vserver-delete' |
  'security-session-limit-vserver-get-iter' |
  'security-session-limit-vserver-modify' |
  'security-session-location-stats-get-iter' |
  'security-session-request-stats-get-iter' |
  'security-session-reset-statistics' |
  'security-session-running-stats-get-iter' |
  'security-session-user-stats-get-iter' |
  'security-session-vserver-stats-get-iter' |
  'security-ssh-add' |
  'security-ssh-get-iter' |
  'security-ssh-remove' |
  'security-ssl-get-iter' |
  'security-ssl-modify' |
  'security-tpm-clear' |
  'security-tpm-reset' |
  'security-tpm-status-get-iter' |
  'security-trace-filter-get-iter' |
  'security-trace-result-show' |
  'service-processor-api-service-disable-installed-certificates' |
  'service-processor-api-service-enable-installed-certificates' |
  'service-processor-api-service-get' |
  'service-processor-api-service-modify' |
  'service-processor-api-service-renew-internal-certificates' |
  'service-processor-asup-config-get' |
  'service-processor-asup-config-set' |
  'service-processor-asup-invoke' |
  'service-processor-auto-configuration-disable' |
  'service-processor-auto-configuration-enable' |
  'service-processor-auto-configuration-get' |
  'service-processor-get' |
  'service-processor-get-iter' |
  'service-processor-image-get' |
  'service-processor-image-modify' |
  'service-processor-image-update' |
  'service-processor-image-update-progress-get' |
  'service-processor-log-allocation-get' |
  'service-processor-log-allocation-get-iter' |
  'service-processor-network-get' |
  'service-processor-network-get-iter' |
  'service-processor-network-modify' |
  'service-processor-network-modify-iter' |
  'service-processor-reboot' |
  'service-processor-ssh-add-allowed-addresses' |
  'service-processor-ssh-get' |
  'service-processor-ssh-remove-allowed-addresses' |
  'sis-get-iter' |
  'sis-policy-get-iter' |
  'sis-prepare-to-downgrade' |
  'sis-status' |
  'snapdiff-rpc-server-get-create-defaults' |
  'snapdiff-rpc-server-get-iter' |
  'snaplock-event-retention-get-iter' |
  'snaplock-event-retention-policy-get-iter' |
  'snaplock-get-clock-ntp-sync' |
  'snaplock-get-node-compliance-clock' |
  'snaplock-get-vserver-active-log-files-iter' |
  'snaplock-get-vserver-log-iter' |
  'snaplock-legal-hold-get-iter' |
  'snaplock-modify-clock-ntp-sync' |
  'snaplock-set-node-compliance-clock' |
  'snapmirror-abort' |
  'snapmirror-abort-async' |
  'snapmirror-abort-iter' |
  'snapmirror-auto-protect-add-exclude' |
  'snapmirror-auto-protect-off' |
  'snapmirror-auto-protect-on' |
  'snapmirror-auto-protect-remove-exclude' |
  'snapmirror-break' |
  'snapmirror-break-async' |
  'snapmirror-break-iter' |
  'snapmirror-cache-rebuild-relationship' |
  'snapmirror-capabilities-get' |
  'snapmirror-capabilities-get-iter' |
  'snapmirror-check' |
  'snapmirror-check-iter' |
  'snapmirror-config-replication-cluster-storage-configuration-get' |
  'snapmirror-config-replication-cluster-storage-configuration-modify' |
  'snapmirror-cr-status-aggregate-eligibility-get' |
  'snapmirror-cr-status-aggregate-eligibility-get-iter' |
  'snapmirror-cr-status-comm-get' |
  'snapmirror-cr-status-comm-get-iter' |
  'snapmirror-cr-status-get' |
  'snapmirror-create' |
  'snapmirror-destroy' |
  'snapmirror-destroy-async' |
  'snapmirror-destroy-iter' |
  'snapmirror-get' |
  'snapmirror-get-destination' |
  'snapmirror-get-destination-iter' |
  'snapmirror-get-dp-personality' |
  'snapmirror-get-iter' |
  'snapmirror-get-total-records' |
  'snapmirror-get-volume-status' |
  'snapmirror-history-get' |
  'snapmirror-history-get-iter' |
  'snapmirror-initialize' |
  'snapmirror-initialize-iter' |
  'snapmirror-initialize-ls-set' |
  'snapmirror-list-unprotected' |
  'snapmirror-modify' |
  'snapmirror-modify-iter' |
  'snapmirror-object-store-config-create' |
  'snapmirror-object-store-config-get-iter' |
  'snapmirror-object-store-config-modify' |
  'snapmirror-object-store-endpoint-delete' |
  'snapmirror-policy-get-iter' |
  'snapmirror-promote' |
  'snapmirror-promote-iter' |
  'snapmirror-protect' |
  'snapmirror-quiesce' |
  'snapmirror-quiesce-iter' |
  'snapmirror-release' |
  'snapmirror-release-iter' |
  'snapmirror-restore' |
  'snapmirror-resume' |
  'snapmirror-resume-iter' |
  'snapmirror-resync' |
  'snapmirror-resync-iter' |
  'snapmirror-snapshot-owner-get' |
  'snapmirror-snapshot-owner-get-snapshots' |
  'snapmirror-update' |
  'snapmirror-update-iter' |
  'snapmirror-update-ls-set' |
  'snapshot-get-iter' |
  'snapshot-modify-iter' |
  'snapshot-policy-add-schedule' |
  'snapshot-policy-create' |
  'snapshot-policy-delete' |
  'snapshot-policy-get' |
  'snapshot-policy-get-iter' |
  'snapshot-policy-modify' |
  'snapshot-policy-modify-schedule' |
  'snapshot-policy-remove-schedule' |
  'snapshot-reserve-list-info' |
  'snmp-community-add' |
  'snmp-community-delete' |
  'snmp-community-delete-all' |
  'snmp-disable' |
  'snmp-enable' |
  'snmp-enable-snmpv3' |
  'snmp-get' |
  'snmp-get-next' |
  'snmp-prepare-to-downgrade' |
  'snmp-status' |
  'snmp-test-trap-trigger' |
  'snmp-trap-disable' |
  'snmp-trap-enable' |
  'snmp-traphost-add' |
  'snmp-traphost-delete' |
  'ssh-prepare-to-downgrade' |
  'storage-acp-firmware-file-get-iter' |
  'storage-adapter-enable-adapter' |
  'storage-adapter-get-adapter-info' |
  'storage-adapter-get-adapter-list' |
  'storage-array-get-config-summary' |
  'storage-array-list-info' |
  'storage-array-modify' |
  'storage-array-port-modify' |
  'storage-array-ports-list-info' |
  'storage-array-rename' |
  'storage-bridge-config-dump-collect' |
  'storage-bridge-config-dump-delete' |
  'storage-bridge-config-dump-get-iter' |
  'storage-bridge-coredump-collect' |
  'storage-bridge-coredump-delete' |
  'storage-bridge-coredump-get-iter' |
  'storage-bridge-firmware-firmware-update' |
  'storage-bridge-get' |
  'storage-bridge-get-iter' |
  'storage-disk-firmware-file-get-iter' |
  'storage-disk-get-iter' |
  'storage-disk-remove-reservation' |
  'storage-disk-set-foreign-lun' |
  'storage-disk-setstate' |
  'storage-initiator-balance' |
  'storage-initiator-disk-path-list-info' |
  'storage-initiator-errors-list-info' |
  'storage-initiator-get-load' |
  'storage-initiator-path-list-info' |
  'storage-initiator-path-quiesce' |
  'storage-initiator-path-resume' |
  'storage-iscsi-initiator-add-target' |
  'storage-iscsi-initiator-auth-config-create' |
  'storage-iscsi-initiator-auth-config-delete' |
  'storage-iscsi-initiator-auth-config-get' |
  'storage-iscsi-initiator-auth-config-get-iter' |
  'storage-iscsi-initiator-auth-config-modify' |
  'storage-iscsi-initiator-connect' |
  'storage-iscsi-initiator-disconnect' |
  'storage-iscsi-initiator-get-iter' |
  'storage-iscsi-initiator-remove-target' |
  'storage-iscsi-initiator-session-create' |
  'storage-iscsi-initiator-session-delete' |
  'storage-iscsi-initiator-session-get' |
  'storage-iscsi-initiator-session-get-iter' |
  'storage-iscsi-initiator-session-modify' |
  'storage-iscsi-iswi-initiator-create' |
  'storage-iscsi-iswi-initiator-delete' |
  'storage-iscsi-iswi-initiator-get' |
  'storage-iscsi-iswi-initiator-get-iter' |
  'storage-iscsi-iswi-initiator-modify' |
  'storage-iscsi-iswi-initiator-rename' |
  'storage-pool-add' |
  'storage-pool-aggregate-get-iter' |
  'storage-pool-available-capacity-get-iter' |
  'storage-pool-create' |
  'storage-pool-delete' |
  'storage-pool-disk-get-iter' |
  'storage-pool-get-iter' |
  'storage-pool-reassign' |
  'storage-pool-rename' |
  'storage-port-disable' |
  'storage-port-enable' |
  'storage-port-info-get' |
  'storage-port-info-get-iter' |
  'storage-port-rescan' |
  'storage-port-reset' |
  'storage-port-reset-device' |
  'storage-service-get-iter' |
  'storage-shelf-acp-configure' |
  'storage-shelf-acp-firmware-update' |
  'storage-shelf-acp-firmware-update-info-get' |
  'storage-shelf-acp-firmware-update-info-get-iter' |
  'storage-shelf-acp-get' |
  'storage-shelf-acp-module-get' |
  'storage-shelf-acp-module-get-iter' |
  'storage-shelf-bay-list-info' |
  'storage-shelf-drawer-get' |
  'storage-shelf-drawer-get-iter' |
  'storage-shelf-drawer-phy-get' |
  'storage-shelf-drawer-phy-get-iter' |
  'storage-shelf-drawer-slot-get' |
  'storage-shelf-drawer-slot-get-iter' |
  'storage-shelf-environment-list-info' |
  'storage-shelf-error-list-info' |
  'storage-shelf-firmware-file-get-iter' |
  'storage-shelf-firmware-update' |
  'storage-shelf-firmware-update-info-get' |
  'storage-shelf-firmware-update-info-get-iter' |
  'storage-shelf-get-shelf-info' |
  'storage-shelf-identify' |
  'storage-shelf-info-get' |
  'storage-shelf-info-get-iter' |
  'storage-shelf-list-info' |
  'storage-shelf-location-led-get' |
  'storage-shelf-location-led-get-iter' |
  'storage-shelf-location-led-modify' |
  'storage-shelf-location-led-modify-iter' |
  'storage-switch-get' |
  'storage-switch-get-iter' |
  'storage-transition-aggregates-get-iter' |
  'storage-transition-aggregates-start' |
  'storage-transition-commit-get-iter' |
  'storage-transition-commit-start' |
  'storage-transition-pre-commit-begin' |
  'storage-transition-pre-commit-end' |
  'storage-transition-pre-commit-get' |
  'storage-transition-pre-commit-get-iter' |
  'storage-transition-purge-info' |
  'storage-transition-revert-get-iter' |
  'storage-transition-revert-start' |
  'storage-transition-volumes-get-iter' |
  'storage-transition-volumes-start' |
  'system-api-change-get-iter' |
  'system-api-get-elements' |
  'system-api-list' |
  'system-api-list-types' |
  'system-cache-mirror-disable' |
  'system-cache-mirror-enable' |
  'system-cache-mirror-get' |
  'system-cache-mirror-get-iter' |
  'system-cli' |
  'system-get-node-info-iter' |
  'system-get-ontapi-version' |
  'system-get-vendor-info' |
  'system-get-version' |
  'system-hypervisor-host-config-create' |
  'system-hypervisor-host-config-destroy' |
  'system-hypervisor-host-config-get' |
  'system-hypervisor-host-config-get-iter' |
  'system-hypervisor-host-config-modify' |
  'system-hypervisor-snmpv3-config-create' |
  'system-hypervisor-snmpv3-config-destroy' |
  'system-hypervisor-snmpv3-config-get' |
  'system-hypervisor-snmpv3-config-get-iter' |
  'system-hypervisor-snmpv3-config-modify' |
  'system-hypervisor-uplink-mapping-create' |
  'system-hypervisor-uplink-mapping-destroy' |
  'system-hypervisor-uplink-mapping-get' |
  'system-hypervisor-uplink-mapping-modify' |
  'system-image-external-package-delete' |
  'system-image-external-package-get-iter' |
  'system-image-fetch-package' |
  'system-image-get-iter' |
  'system-image-modify' |
  'system-image-package-delete' |
  'system-image-package-get-iter' |
  'system-image-update' |
  'system-image-update-get-abort' |
  'system-image-update-progress-get' |
  'system-license-aggregate-get-iter' |
  'system-manager-upgrade' |
  'system-netconsole-get' |
  'system-netconsole-modify' |
  'system-node-discovery-get-iter' |
  'system-node-get' |
  'system-node-get-iter' |
  'system-node-modify' |
  'system-node-power-cycle' |
  'system-node-power-get' |
  'system-node-power-off' |
  'system-node-power-on' |
  'system-node-reboot' |
  'system-node-rename' |
  'system-node-reset' |
  'system-node-revert-to' |
  'system-node-shutdown' |
  'system-ontapi-limits-get' |
  'system-ontapi-limits-set' |
  'system-services-web-file-uploads-config-get' |
  'system-services-web-file-uploads-config-modify' |
  'system-services-web-file-uploads-delete-file' |
  'system-services-web-file-uploads-get' |
  'system-services-web-file-uploads-get-iter' |
  'system-services-web-file-uploads-get-total-records' |
  'system-services-web-file-uploads-move-file' |
  'system-services-web-get' |
  'system-services-web-node-get' |
  'system-services-web-node-get-iter' |
  'system-status-hypervisor-get' |
  'system-status-hypervisor-modify' |
  'system-status-restart-restart-service' |
  'system-status-service-get-iter' |
  'system-user-capability-get-iter' |
  'system-zapi-quarantine-queue-stats-get' |
  'system-zapi-quarantine-queue-stats-get-iter' |
  'system-zapi-queue-counts-get' |
  'system-zapi-queue-counts-get-iter' |
  'system-zapi-queue-times-get' |
  'system-zapi-queue-times-get-iter' |
  'tape-mc-get' |
  'tape-mc-get-iter' |
  'tape-mc-info-alias-clear' |
  'tape-mc-info-alias-set' |
  'tape-mc-info-offline' |
  'tape-mc-info-online' |
  'tape-mc-info-position' |
  'tape-mc-info-reset' |
  'tape-mc-info-test-release' |
  'tape-mc-info-test-reserve' |
  'tape-mc-info-trace' |
  'template-management-choices-get' |
  'template-management-template-copy' |
  'template-management-template-delete' |
  'template-management-template-download' |
  'template-management-template-get' |
  'template-management-template-get-iter' |
  'template-management-template-parameter-get' |
  'template-management-template-parameter-get-iter' |
  'template-management-template-parameter-modify' |
  'template-management-template-parameter-modify-iter' |
  'template-management-template-provision' |
  'template-management-template-provision-error-clean' |
  'template-management-template-provision-error-get' |
  'template-management-template-read' |
  'template-management-template-refresh' |
  'template-management-template-rename' |
  'template-management-template-upload' |
  'test-intrinsic-apis-1-create' |
  'test-intrinsic-apis-1-destroy' |
  'test-intrinsic-apis-1-destroy-iter' |
  'test-intrinsic-apis-1-get' |
  'test-intrinsic-apis-1-get-create-defaults' |
  'test-intrinsic-apis-1-get-iter' |
  'test-intrinsic-apis-1-get-total-records' |
  'test-intrinsic-apis-1-list-info' |
  'test-intrinsic-apis-2-create' |
  'test-intrinsic-apis-2-destroy' |
  'test-intrinsic-apis-2-destroy-iter' |
  'test-intrinsic-apis-2-get' |
  'test-intrinsic-apis-2-get-create-defaults' |
  'test-intrinsic-apis-2-get-iter' |
  'test-intrinsic-apis-2-get-total-records' |
  'test-intrinsic-apis-2-list-info' |
  'test-intrinsic-apis-2-modify' |
  'test-intrinsic-apis-2-modify-iter' |
  'test-intrinsic-apis-3-create' |
  'test-intrinsic-apis-3-destroy' |
  'test-intrinsic-apis-3-destroy-iter' |
  'test-intrinsic-apis-3-get' |
  'test-intrinsic-apis-3-get-create-defaults' |
  'test-intrinsic-apis-3-get-iter' |
  'test-intrinsic-apis-3-get-total-records' |
  'test-intrinsic-apis-3-list-info' |
  'test-intrinsic-apis-4-create' |
  'test-intrinsic-apis-4-destroy' |
  'test-intrinsic-apis-4-destroy-iter' |
  'test-intrinsic-apis-4-get' |
  'test-intrinsic-apis-4-get-create-defaults' |
  'test-intrinsic-apis-4-get-iter' |
  'test-intrinsic-apis-4-get-total-records' |
  'test-intrinsic-apis-4-list-info' |
  'test-key-optionality-alt-create' |
  'test-key-optionality-alt-destroy' |
  'test-key-optionality-alt-get' |
  'test-key-optionality-alt-modify' |
  'test-key-optionality-create' |
  'test-key-optionality-destroy' |
  'test-key-optionality-get' |
  'test-key-optionality-modify' |
  'test-memory-stats' |
  'test-password-get' |
  'test-password-set' |
  'test-plug-leak' |
  'test-ro-action-1-readonly3' |
  'test-ro-action-2-readonly4' |
  'test-ro-action-3-writable3' |
  'test-ro-method-readonly1' |
  'test-ro-table-readonly1' |
  'test-ro-table-writable1' |
  'test-rw-method-writable2' |
  'test-schema-validator' |
  'test-zapi-ro-view-1-readonly6' |
  'test-zapi-ro-view-1-writable4' |
  'test-zapi-ro-view-5-create' |
  'test-zapi-ro-view-5-destroy' |
  'test-zapi-ro-view-5-destroy-iter' |
  'test-zapi-ro-view-5-get' |
  'test-zapi-ro-view-5-get-create-defaults' |
  'test-zapi-ro-view-5-get-iter' |
  'test-zapi-ro-view-5-get-total-records' |
  'test-zapi-ro-view-5-list-info' |
  'test-zapi-ro-view-6-create' |
  'test-zapi-ro-view-6-destroy' |
  'test-zapi-ro-view-6-destroy-iter' |
  'test-zapi-ro-view-6-get' |
  'test-zapi-ro-view-6-get-create-defaults' |
  'test-zapi-ro-view-6-get-iter' |
  'test-zapi-ro-view-6-get-total-records' |
  'test-zapi-ro-view-6-list-info' |
  'test-zapi-ro-view-6-modify' |
  'test-zapi-ro-view-6-modify-iter' |
  'test-zapi-sleep' |
  'test-zapi-sleep-destroy-async-iter' |
  'test-zapi-sleep-destroy-iter' |
  'test-zapi-sleep-get-iter' |
  'test-zapi-sleep-method-async-iter' |
  'test-zapi-sleep-method-iter' |
  'test-zapi-sleep-modify-async-iter' |
  'test-zapi-sleep-modify-iter' |
  'test-zapi-smf-mapping-apis-async-create' |
  'test-zapi-smf-mapping-apis-async-destroy' |
  'test-zapi-smf-mapping-apis-async-destroy-iter' |
  'test-zapi-smf-mapping-apis-async-get' |
  'test-zapi-smf-mapping-apis-async-get-create-defaults' |
  'test-zapi-smf-mapping-apis-async-get-iter' |
  'test-zapi-smf-mapping-apis-async-get-total-records' |
  'test-zapi-smf-mapping-apis-async-list-info' |
  'test-zapi-smf-mapping-apis-async-modify' |
  'test-zapi-smf-mapping-apis-async-modify-iter' |
  'test-zapi-smf-mapping-apis-create' |
  'test-zapi-smf-mapping-apis-destroy' |
  'test-zapi-smf-mapping-apis-destroy-iter' |
  'test-zapi-smf-mapping-apis-get' |
  'test-zapi-smf-mapping-apis-get-create-defaults' |
  'test-zapi-smf-mapping-apis-get-iter' |
  'test-zapi-smf-mapping-apis-get-total-records' |
  'test-zapi-smf-mapping-apis-list-info' |
  'test-zapi-smf-mapping-apis-method-only-async-iter' |
  'test-zapi-smf-mapping-apis-method-only-async-no-query' |
  'test-zapi-smf-mapping-apis-method-only-create' |
  'test-zapi-smf-mapping-apis-method-only-default' |
  'test-zapi-smf-mapping-apis-method-only-default-iter' |
  'test-zapi-smf-mapping-apis-method-only-get' |
  'test-zapi-smf-mapping-apis-modify' |
  'test-zapi-smf-mapping-apis-modify-iter' |
  'ucm-adapter-get' |
  'ucm-adapter-get-iter' |
  'ucm-adapter-modify' |
  'unit-test-ktest-run' |
  'virtual-machine-get-info' |
  'virtual-machine-maintenance-event-acknowlege' |
  'virtual-machine-maintenance-event-get' |
  'virtual-machine-maintenance-event-get-iter' |
  'virtual-machine-system-disks-get-iter' |
  'vm-disk-object-store-create' |
  'vm-disk-object-store-destroy' |
  'vm-disk-object-store-dns-cache-create' |
  'vm-disk-object-store-dns-cache-destroy' |
  'vm-disk-object-store-dns-cache-get-iter' |
  'vm-disk-object-store-dns-cache-modify' |
  'vm-disk-object-store-get-iter' |
  'vm-disk-object-store-modify' |
  'vm-network-load-balancer-get-iter' |
  'vmservices-vsphere-credential-check' |
  'vmservices-vsphere-credential-get' |
  'vmservices-vsphere-credential-modify' |
  'volume-aggregate-vacate-async' |
  'volume-autobalance-get-iter' |
  'volume-clone-create' |
  'volume-clone-create-async' |
  'volume-clone-get-iter' |
  'volume-encryption-conversion-get-iter' |
  'volume-encryption-rekey-get-iter' |
  'volume-flexgroup-capacity-tier-footprint-get-iter' |
  'volume-flexgroup-deploy-async' |
  'volume-footprint-get-iter' |
  'volume-get-iter' |
  'volume-modify-iter' |
  'volume-modify-iter-async' |
  'volume-move-get-iter' |
  'volume-move-modify' |
  'volume-move-pause' |
  'volume-move-resume' |
  'volume-move-start' |
  'volume-move-target-aggr-get-iter' |
  'volume-move-trigger-abort' |
  'volume-move-trigger-cutover' |
  'volume-prepare-for-revert' |
  'volume-recovery-queue-get' |
  'volume-recovery-queue-get-iter' |
  'volume-recovery-queue-modify-retention' |
  'volume-recovery-queue-purge' |
  'volume-recovery-queue-recover' |
  'volume-rehost' |
  'volume-space-get-iter' |
  'volume-storage-service-get-iter' |
  'volume-tiering-policies-list' |
  'volume-transition' |
  'volume-transition-prepare-to-downgrade' |
  'volume-transition-protect' |
  'vscan-active-scanner-pool-get-iter' |
  'vscan-connection-extended-stats-get-iter' |
  'vscan-connection-status-all-get-iter' |
  'vscan-events-get-iter' |
  'vscan-on-access-policy-get-iter' |
  'vscan-on-demand-report-get-iter' |
  'vscan-on-demand-task-get-iter' |
  'vscan-scanner-pool-get-iter' |
  'vscan-status-get-iter' |
  'vserver-add-aggregates' |
  'vserver-add-protocols' |
  'vserver-config-diff-get' |
  'vserver-config-diff-get-iter' |
  'vserver-create' |
  'vserver-create-async' |
  'vserver-destroy' |
  'vserver-destroy-async' |
  'vserver-get-iter' |
  'vserver-lock' |
  'vserver-login-banner-get-iter' |
  'vserver-login-banner-modify-iter' |
  'vserver-migrate-cleanup' |
  'vserver-migrate-cutover' |
  'vserver-migrate-debug-launch-check-job' |
  'vserver-migrate-get' |
  'vserver-migrate-get-iter' |
  'vserver-migrate-pause' |
  'vserver-migrate-resume' |
  'vserver-migrate-start' |
  'vserver-migrate-volume-get' |
  'vserver-migrate-volume-get-iter' |
  'vserver-modify' |
  'vserver-modify-iter' |
  'vserver-motd-get-iter' |
  'vserver-motd-modify-iter' |
  'vserver-peer-accept' |
  'vserver-peer-create' |
  'vserver-peer-delete' |
  'vserver-peer-get-iter' |
  'vserver-peer-modify' |
  'vserver-peer-modify-local-name' |
  'vserver-peer-permission-create' |
  'vserver-peer-permission-delete' |
  'vserver-peer-permission-get' |
  'vserver-peer-permission-get-iter' |
  'vserver-peer-permission-modify' |
  'vserver-peer-permission-remote-get' |
  'vserver-peer-permission-remote-get-iter' |
  'vserver-peer-reject' |
  'vserver-peer-repair-peer-name' |
  'vserver-peer-resume' |
  'vserver-peer-suspend' |
  'vserver-peer-transition-create' |
  'vserver-peer-transition-destroy' |
  'vserver-peer-transition-destroy-iter' |
  'vserver-peer-transition-get' |
  'vserver-peer-transition-get-iter' |
  'vserver-peer-transition-modify' |
  'vserver-protect-precheck' |
  'vserver-protect-precheck-dp-support' |
  'vserver-protect-precheck-network' |
  'vserver-protect-precheck-vge-support' |
  'vserver-remove-aggregates' |
  'vserver-remove-protocols' |
  'vserver-rename' |
  'vserver-rename-async' |
  'vserver-saninit' |
  'vserver-show-aggr-get-iter' |
  'vserver-start' |
  'vserver-stop' |
  'vserver-unlock' |
  'vvol-clone-create' |
  'vvol-create' |
  'vvol-delete' |
  'vvol-get-iter' |
  'vvol-get-op-status' |
  'vvol-mapping-create' |
  'vvol-perf-policy-modify';
