export type NetappSdkVfilerFunctions =
  'active-directory-account-create' |
  'active-directory-account-delete' |
  'active-directory-account-get-iter' |
  'active-directory-account-modify' |
  'active-directory-account-password-change' |
  'active-directory-account-password-reset' |
  'application-create-async' |
  'application-delete-async' |
  'application-details-get-iter' |
  'application-get-iter' |
  'application-lun-get-iter' |
  'application-modify-async' |
  'application-modify-via-template-async' |
  'application-provisioning-job-get-iter' |
  'application-provisioning-lun-results-get' |
  'application-provisioning-lun-start' |
  'application-provisioning-volume-results-get' |
  'application-provisioning-volume-start' |
  'application-rename' |
  'application-snapshot-create' |
  'application-snapshot-delete' |
  'application-snapshot-get-iter' |
  'application-snapshot-restore' |
  'application-stats-get-iter' |
  'application-supported-aggr-by-restraint-get-iter' |
  'application-template-get-iter' |
  'application-test-vvolengine-can-change-performance' |
  'application-test-vvolengine-place' |
  'application-volume-get-iter' |
  'application-vserver-supported' |
  'application-vserver-supported-get-iter' |
  'autogenzapi2-create' |
  'autogenzapi2-destroy' |
  'autogenzapi2-get-iter' |
  'autogenzapi2-modify' |
  'av-on-access-policy-create' |
  'av-on-access-policy-delete' |
  'av-on-access-policy-get' |
  'av-on-access-policy-get-iter' |
  'av-on-access-policy-modify' |
  'av-on-demand-command-scan-dir-create' |
  'av-on-demand-command-scan-dir-delete' |
  'av-on-demand-command-scan-dir-get' |
  'av-on-demand-command-scan-dir-get-iter' |
  'av-on-demand-command-scan-dir-modify' |
  'av-on-demand-command-scan-file-create' |
  'av-on-demand-command-scan-file-delete' |
  'av-on-demand-command-scan-file-get' |
  'av-on-demand-command-scan-file-get-iter' |
  'av-on-demand-command-scan-file-modify' |
  'av-on-demand-command-scan-vserver-create' |
  'av-on-demand-command-scan-vserver-delete' |
  'av-on-demand-command-scan-vserver-get' |
  'av-on-demand-command-scan-vserver-get-iter' |
  'av-on-demand-command-scan-vserver-modify' |
  'av-on-demand-job-get-iter' |
  'av-on-demand-report-get-iter' |
  'av-on-demand-report-print' |
  'av-on-demand-report-upload' |
  'cg-commit' |
  'cg-start' |
  'cifs-branchcache-create' |
  'cifs-branchcache-flush' |
  'cifs-branchcache-get' |
  'cifs-branchcache-get-iter' |
  'cifs-branchcache-hash' |
  'cifs-branchcache-modify' |
  'cifs-branchcache-remove' |
  'cifs-character-mapping-create' |
  'cifs-character-mapping-destroy' |
  'cifs-character-mapping-get-iter' |
  'cifs-character-mapping-modify' |
  'cifs-check-server-get-iter' |
  'cifs-connection-get-iter' |
  'cifs-domain-discovered-servers-get-iter' |
  'cifs-domain-discovered-servers-reset' |
  'cifs-domain-name-mapping-search-add' |
  'cifs-domain-name-mapping-search-get-iter' |
  'cifs-domain-name-mapping-search-modify' |
  'cifs-domain-name-mapping-search-remove' |
  'cifs-domain-password-schedule-get-iter' |
  'cifs-domain-password-schedule-modify' |
  'cifs-domain-preferred-dc-add' |
  'cifs-domain-preferred-dc-get-iter' |
  'cifs-domain-preferred-dc-remove' |
  'cifs-domain-server-discovery-mode-get' |
  'cifs-domain-server-discovery-mode-get-iter' |
  'cifs-domain-server-discovery-mode-modify' |
  'cifs-domain-trusts-get-iter' |
  'cifs-domain-trusts-rediscover' |
  'cifs-foo-get-iter' |
  'cifs-home-directory-get-iter' |
  'cifs-home-directory-modify' |
  'cifs-home-directory-search-path-add' |
  'cifs-home-directory-search-path-delete' |
  'cifs-home-directory-search-path-get-iter' |
  'cifs-home-directory-search-path-remove' |
  'cifs-home-directory-search-path-reorder' |
  'cifs-local-group-create' |
  'cifs-local-group-delete' |
  'cifs-local-group-get-iter' |
  'cifs-local-group-members-add-members' |
  'cifs-local-group-members-get-iter' |
  'cifs-local-group-members-remove-members' |
  'cifs-local-group-modify' |
  'cifs-local-group-rename' |
  'cifs-local-user-create' |
  'cifs-local-user-delete' |
  'cifs-local-user-get-iter' |
  'cifs-local-user-membership-get-iter' |
  'cifs-local-user-modify' |
  'cifs-local-user-rename' |
  'cifs-local-user-set-password' |
  'cifs-nbtstat-get-iter' |
  'cifs-options-get-iter' |
  'cifs-options-modify' |
  'cifs-password-change' |
  'cifs-password-reset' |
  'cifs-preferred-dc-check-get-iter' |
  'cifs-privilege-add-privilege' |
  'cifs-privilege-get-iter' |
  'cifs-privilege-remove-privilege' |
  'cifs-privilege-reset-privilege' |
  'cifs-security-get-iter' |
  'cifs-security-modify' |
  'cifs-server-add-netbios-aliases' |
  'cifs-server-create' |
  'cifs-server-delete' |
  'cifs-server-get-iter' |
  'cifs-server-modify' |
  'cifs-server-remove-netbios-aliases' |
  'cifs-server-repair-modify' |
  'cifs-server-start' |
  'cifs-server-stop' |
  'cifs-session-close' |
  'cifs-session-file-close' |
  'cifs-session-file-get-iter' |
  'cifs-session-get-iter' |
  'cifs-shadowcopy-add-files' |
  'cifs-shadowcopy-ems-get-iter' |
  'cifs-shadowcopy-keep-snapshot' |
  'cifs-shadowcopy-restore-dir' |
  'cifs-share-access-control-create' |
  'cifs-share-access-control-delete' |
  'cifs-share-access-control-get-iter' |
  'cifs-share-access-control-modify' |
  'cifs-share-create' |
  'cifs-share-delete' |
  'cifs-share-get-iter' |
  'cifs-share-modify' |
  'cifs-symlink-create' |
  'cifs-symlink-delete' |
  'cifs-symlink-get-iter' |
  'cifs-symlink-modify' |
  'cifs-user-home-directory-path-get' |
  'cifs-user-home-directory-path-get-iter' |
  'cifs-users-and-group-local-group-members-get-iter' |
  'cifs-users-and-group-local-user-membership-get-iter' |
  'cifs-users-and-groups-delete-cifs-lug' |
  'cifs-users-and-groups-get-import-status' |
  'cifs-users-and-groups-load-from-uri' |
  'clock-get-clock' |
  'clock-get-timezone' |
  'clone-autodelete' |
  'clone-autodelete-status' |
  'clone-create' |
  'clone-deletion-add-extension' |
  'clone-deletion-get-iter' |
  'clone-deletion-minimum-size' |
  'clone-deletion-remove-extension' |
  'clone-split-enable' |
  'clone-split-load-get-iter' |
  'clone-split-load-modify' |
  'clone-split-status' |
  'clone-token-create' |
  'clone-token-delete' |
  'clone-token-get' |
  'clone-token-get-iter' |
  'clone-token-modify-expiry-limit' |
  'cluster-application-record-create' |
  'cluster-application-record-delete' |
  'cluster-application-record-delete-iter' |
  'cluster-application-record-get-iter' |
  'cluster-application-record-modify' |
  'cluster-application-record-modify-iter' |
  'dummy-fcp-adapter-initiators-list-info' |
  'dummy-fcp-get-iter' |
  'dummy-vserver-alt-get' |
  'dummy-vserver-create' |
  'dummy-vserver-destroy-iter' |
  'dummy-vserver-dosomething' |
  'dummy-vserver-family-dummy1' |
  'dummy-vserver-family-test-alt-create' |
  'dummy-vserver-family-test-alt-destroy' |
  'dummy-vserver-family-test-alt-get' |
  'dummy-vserver-family-test-alt-list-info' |
  'dummy-vserver-family-test-alt-modify' |
  'dummy-vserver-family-test-create' |
  'dummy-vserver-family-test-destroy' |
  'dummy-vserver-family-test-destroy-iter' |
  'dummy-vserver-family-test-get' |
  'dummy-vserver-family-test-get-iter' |
  'dummy-vserver-family-test-list-info' |
  'dummy-vserver-family-test-modify' |
  'dummy-vserver-family-test-modify-iter' |
  'dummy-vserver-fcp-alt-1-create' |
  'dummy-vserver-fcp-alt-1-delete' |
  'dummy-vserver-fcp-alt-1-get' |
  'dummy-vserver-fcp-alt-1-modify' |
  'dummy-vserver-fcp-alt-create' |
  'dummy-vserver-fcp-alt-delete' |
  'dummy-vserver-fcp-alt-get' |
  'dummy-vserver-fcp-alt-modify' |
  'dummy-vserver-fcp-create' |
  'dummy-vserver-fcp-delete' |
  'dummy-vserver-fcp-get' |
  'dummy-vserver-fcp-list-get-iter' |
  'dummy-vserver-fcp-modify' |
  'dummy-vserver-fcp-service-create' |
  'dummy-vserver-fcp-service-pause' |
  'dummy-vserver-fcp-service-start' |
  'dummy-vserver-fcp-service-stop' |
  'dummy-vserver-file-alt-dummy-vserver-read-file-alternate' |
  'dummy-vserver-get' |
  'dummy-vserver-get-iter' |
  'dummy-vserver-list-info' |
  'dummy-vserver-list-info-1-alt' |
  'dummy-vserver-list-info-2-alt' |
  'dummy-vserver-list-info-3-alt' |
  'dummy-vserver-list-info-alt' |
  'dummy-vserver-modify-iter' |
  'dummylun-destroy-iter' |
  'dummylun-get' |
  'dummylun-get-alt' |
  'dummylun-get-iter' |
  'dummylun-get-iter-alt' |
  'dummylun-list-info' |
  'dummylun-list-info-alt' |
  'dummylun-list-info-alt1' |
  'dummylun-list-info-alt2' |
  'dummylun-modify' |
  'ems-autosupport-log' |
  'export-check-access-get-iter' |
  'export-policy-create' |
  'export-policy-destroy' |
  'export-policy-get' |
  'export-policy-get-iter' |
  'export-policy-rename' |
  'export-rule-add-clientmatches' |
  'export-rule-create' |
  'export-rule-destroy' |
  'export-rule-get' |
  'export-rule-get-create-defaults' |
  'export-rule-get-iter' |
  'export-rule-modify' |
  'export-rule-remove-clientmatches' |
  'export-rule-set-index' |
  'exports-access-cache-config-get' |
  'exports-access-cache-config-get-iter' |
  'exports-access-cache-config-modify' |
  'exports-access-cache-config-reset-to-defaults' |
  'fcp-initiator-get-iter' |
  'fcp-interface-get-iter' |
  'fcp-nameserver-get-iter' |
  'fcp-node-get-name' |
  'fcp-node-set-name' |
  'fcp-ping-igroup-view-get-iter' |
  'fcp-ping-initiator-get-iter' |
  'fcp-port-name-get-iter' |
  'fcp-port-name-set' |
  'fcp-service-create' |
  'fcp-service-destroy' |
  'fcp-service-get-iter' |
  'fcp-service-start' |
  'fcp-service-status' |
  'fcp-service-stop' |
  'fcp-topology-get-iter' |
  'fcp-wwpnalias-get-iter' |
  'fcp-wwpnalias-remove' |
  'fcp-wwpnalias-set' |
  'feature-status-list-info' |
  'file-copy-destroy' |
  'file-copy-get-iter' |
  'file-copy-start' |
  'file-create-directory' |
  'file-create-symlink' |
  'file-delete-directory' |
  'file-delete-file' |
  'file-directory-effective-permissions-get' |
  'file-directory-security-get' |
  'file-directory-security-ntfs-create' |
  'file-directory-security-ntfs-dacl-add' |
  'file-directory-security-ntfs-dacl-get-iter' |
  'file-directory-security-ntfs-dacl-modify' |
  'file-directory-security-ntfs-dacl-remove' |
  'file-directory-security-ntfs-delete' |
  'file-directory-security-ntfs-get-iter' |
  'file-directory-security-ntfs-modify' |
  'file-directory-security-ntfs-sacl-add' |
  'file-directory-security-ntfs-sacl-get-iter' |
  'file-directory-security-ntfs-sacl-modify' |
  'file-directory-security-ntfs-sacl-remove' |
  'file-directory-security-policy-create' |
  'file-directory-security-policy-delete' |
  'file-directory-security-policy-get-iter' |
  'file-directory-security-policy-task-add' |
  'file-directory-security-policy-task-get-iter' |
  'file-directory-security-policy-task-modify' |
  'file-directory-security-policy-task-remove' |
  'file-directory-security-remove-slag' |
  'file-directory-security-set' |
  'file-fingerprint-abort' |
  'file-fingerprint-dump' |
  'file-fingerprint-get-iter' |
  'file-fingerprint-start' |
  'file-get-file-info' |
  'file-get-space-reservation-info' |
  'file-hole-range-query-iter' |
  'file-inode-info-get-iter' |
  'file-list-directory-iter' |
  'file-move-destroy' |
  'file-move-get-iter' |
  'file-move-start' |
  'file-punch-hole-iter' |
  'file-read-file' |
  'file-read-symlink' |
  'file-rename-file' |
  'file-set-space-reservation-info' |
  'file-truncate-file' |
  'file-usage-get' |
  'file-usage-result-get' |
  'file-usage-start' |
  'file-write-file' |
  'fileservice-audit-config-create' |
  'fileservice-audit-config-get' |
  'fileservice-audit-config-get-iter' |
  'fileservice-audit-config-modify' |
  'fileservice-audit-disable' |
  'fileservice-audit-enable' |
  'fileservice-audit-remove' |
  'fileservice-audit-repair' |
  'fileservice-audit-rotate-log' |
  'flexcache-connected-cache-get-iter' |
  'flexcache-create-async' |
  'flexcache-destroy-async' |
  'flexcache-get-iter' |
  'flexcache-origin-cleanup-cache-relationship' |
  'flexcache-origin-config-get-iter' |
  'flexcache-origin-config-modify' |
  'fpolicy-disable-policy' |
  'fpolicy-enable-policy' |
  'fpolicy-passthrough-read-connection-get-iter' |
  'fpolicy-policy-create' |
  'fpolicy-policy-delete' |
  'fpolicy-policy-event-create' |
  'fpolicy-policy-event-delete' |
  'fpolicy-policy-event-get-iter' |
  'fpolicy-policy-event-modify' |
  'fpolicy-policy-external-engine-create' |
  'fpolicy-policy-external-engine-delete' |
  'fpolicy-policy-external-engine-get-iter' |
  'fpolicy-policy-external-engine-modify' |
  'fpolicy-policy-get-iter' |
  'fpolicy-policy-modify' |
  'fpolicy-policy-scope-create' |
  'fpolicy-policy-scope-delete' |
  'fpolicy-policy-scope-get-iter' |
  'fpolicy-policy-scope-modify' |
  'fpolicy-policy-status-get-iter' |
  'fpolicy-server-connect' |
  'fpolicy-server-disconnect' |
  'fpolicy-server-status-get-iter' |
  'gpo-applied-info-get-iter' |
  'gpo-get-iter' |
  'gpo-gpresult-info-get-iter' |
  'gpo-modify' |
  'gpo-restricted-group-applied-info-get-iter' |
  'gpo-restricted-group-defined-info-get-iter' |
  'gpo-update' |
  'group-mapping-create' |
  'group-mapping-delete' |
  'group-mapping-get-iter' |
  'group-mapping-insert' |
  'group-mapping-modify' |
  'group-mapping-swap' |
  'igroup-add' |
  'igroup-bind-portset' |
  'igroup-create' |
  'igroup-destroy' |
  'igroup-disable-aix-support' |
  'igroup-get-iter' |
  'igroup-lookup-lun' |
  'igroup-remove' |
  'igroup-rename' |
  'igroup-set-attribute' |
  'igroup-unbind-portset' |
  'iscsi-add' |
  'iscsi-auth-add-initiator-address-ranges' |
  'iscsi-auth-generate-chap-password' |
  'iscsi-auth-remove-initiator-address-ranges' |
  'iscsi-connection-get-iter' |
  'iscsi-connection-shutdown' |
  'iscsi-delete' |
  'iscsi-initiator-add-auth' |
  'iscsi-initiator-auth-get-iter' |
  'iscsi-initiator-delete-auth' |
  'iscsi-initiator-get-auth' |
  'iscsi-initiator-get-default-auth' |
  'iscsi-initiator-get-iter' |
  'iscsi-initiator-modify-chap-params' |
  'iscsi-initiator-set-default-auth' |
  'iscsi-interface-accesslist-add' |
  'iscsi-interface-accesslist-get-iter' |
  'iscsi-interface-accesslist-remove' |
  'iscsi-interface-disable' |
  'iscsi-interface-enable' |
  'iscsi-interface-get-iter' |
  'iscsi-interface-modify' |
  'iscsi-isns-config' |
  'iscsi-isns-create' |
  'iscsi-isns-destroy' |
  'iscsi-isns-get-info' |
  'iscsi-isns-get-iter' |
  'iscsi-isns-start' |
  'iscsi-isns-stop' |
  'iscsi-isns-update' |
  'iscsi-node-get-name' |
  'iscsi-node-set-name' |
  'iscsi-query' |
  'iscsi-remove' |
  'iscsi-service-create' |
  'iscsi-service-destroy' |
  'iscsi-service-get-iter' |
  'iscsi-service-modify' |
  'iscsi-service-start' |
  'iscsi-service-status' |
  'iscsi-service-stop' |
  'iscsi-session-get-iter' |
  'iscsi-session-shutdown' |
  'iscsi-stats-get-iter' |
  'iscsi-target-alias-clear-alias' |
  'iscsi-target-alias-get-alias' |
  'iscsi-target-alias-set-alias' |
  'iscsi-tpgroup-create' |
  'iscsi-tpgroup-destroy' |
  'iscsi-tpgroup-get-iter' |
  'iscsi-tpgroup-interface-add' |
  'iscsi-tpgroup-interface-delete' |
  'job-by-node-get' |
  'job-by-node-get-iter' |
  'job-completed-get' |
  'job-completed-get-iter' |
  'job-delete' |
  'job-delete-iter' |
  'job-expunge' |
  'job-expunge-iter' |
  'job-get' |
  'job-get-iter' |
  'job-history-get' |
  'job-history-get-iter' |
  'job-pause' |
  'job-pause-iter' |
  'job-private-completed-get' |
  'job-private-completed-get-iter' |
  'job-private-delete' |
  'job-private-delete-iter' |
  'job-private-get' |
  'job-private-get-iter' |
  'job-private-pause' |
  'job-private-pause-iter' |
  'job-private-resume' |
  'job-private-resume-iter' |
  'job-private-soft-pause' |
  'job-private-soft-pause-iter' |
  'job-private-stop' |
  'job-private-stop-iter' |
  'job-private-watch-progress' |
  'job-resume' |
  'job-resume-iter' |
  'job-schedule-cron-create' |
  'job-schedule-cron-destroy' |
  'job-schedule-cron-destroy-iter' |
  'job-schedule-cron-get' |
  'job-schedule-cron-get-iter' |
  'job-schedule-cron-modify' |
  'job-schedule-get' |
  'job-schedule-get-iter' |
  'job-schedule-interval-create' |
  'job-schedule-interval-destroy' |
  'job-schedule-interval-destroy-iter' |
  'job-schedule-interval-get' |
  'job-schedule-interval-get-iter' |
  'job-schedule-interval-modify' |
  'job-soft-pause' |
  'job-soft-pause-iter' |
  'job-stop' |
  'job-stop-iter' |
  'job-unclaim' |
  'job-unclaim-iter' |
  'kerberos-config-get' |
  'kerberos-config-get-iter' |
  'kerberos-config-modify' |
  'kerberos-realm-create' |
  'kerberos-realm-delete' |
  'kerberos-realm-get-iter' |
  'kerberos-realm-modify' |
  'ldap-check-get-iter' |
  'ldap-client-create' |
  'ldap-client-delete' |
  'ldap-client-get-iter' |
  'ldap-client-modify' |
  'ldap-client-schema-copy' |
  'ldap-client-schema-delete' |
  'ldap-client-schema-get-iter' |
  'ldap-client-schema-modify' |
  'ldap-config-create' |
  'ldap-config-delete' |
  'ldap-config-get-iter' |
  'ldap-config-modify' |
  'lock-break-iter' |
  'lock-get-iter' |
  'lun-alignment-get-iter' |
  'lun-alignment-reset-statistics' |
  'lun-bind' |
  'lun-bind-get-iter' |
  'lun-clear-persistent-reservation-info' |
  'lun-copy-cancel' |
  'lun-copy-get-iter' |
  'lun-copy-modify' |
  'lun-copy-pause' |
  'lun-copy-resume' |
  'lun-copy-start' |
  'lun-create-by-size' |
  'lun-create-from-file' |
  'lun-destroy' |
  'lun-generate-serial' |
  'lun-get-attribute' |
  'lun-get-attributes' |
  'lun-get-comment' |
  'lun-get-geometry' |
  'lun-get-inquiry-info' |
  'lun-get-iter' |
  'lun-get-maxsize' |
  'lun-get-minsize' |
  'lun-get-occupied-size' |
  'lun-get-persistent-reservation-info' |
  'lun-get-select-attribute' |
  'lun-get-serial-number' |
  'lun-get-space-reservation-info' |
  'lun-get-vdisk-attributes' |
  'lun-has-scsi-reservations' |
  'lun-initiator-list-map-info' |
  'lun-initiator-logged-in' |
  'lun-lba-hole-range-query' |
  'lun-lba-is-hole' |
  'lun-lun-rescan' |
  'lun-map' |
  'lun-map-add-reporting-nodes' |
  'lun-map-get-iter' |
  'lun-map-list-info' |
  'lun-map-remove-reporting-nodes' |
  'lun-move' |
  'lun-move-cancel' |
  'lun-move-get-iter' |
  'lun-move-modify' |
  'lun-move-pause' |
  'lun-move-resume' |
  'lun-move-start' |
  'lun-offline' |
  'lun-online' |
  'lun-port-has-scsi-reservations' |
  'lun-read-raw' |
  'lun-resize' |
  'lun-set-attribute' |
  'lun-set-comment' |
  'lun-set-device-id' |
  'lun-set-qos-policy-group' |
  'lun-set-select-attribute' |
  'lun-set-serial-number' |
  'lun-set-space-alloc' |
  'lun-set-space-reservation-info' |
  'lun-stats-get-iter' |
  'lun-test-vdisk-size' |
  'lun-testmap' |
  'lun-unbind' |
  'lun-unmap' |
  'lun-unset-attribute' |
  'lun-unset-device-id' |
  'lun-write-raw' |
  'name-mapping-create' |
  'name-mapping-delete' |
  'name-mapping-get-iter' |
  'name-mapping-insert' |
  'name-mapping-modify' |
  'name-mapping-refresh-hostname' |
  'name-mapping-swap' |
  'name-mapping-unix-group-add-user' |
  'name-mapping-unix-group-add-users' |
  'name-mapping-unix-group-create' |
  'name-mapping-unix-group-delete-user' |
  'name-mapping-unix-group-destroy' |
  'name-mapping-unix-group-get' |
  'name-mapping-unix-group-get-iter' |
  'name-mapping-unix-group-modify' |
  'name-mapping-unix-user-create' |
  'name-mapping-unix-user-destroy' |
  'name-mapping-unix-user-get' |
  'name-mapping-unix-user-get-iter' |
  'name-mapping-unix-user-modify' |
  'name-service-cache-group-membership-settings-get' |
  'name-service-cache-group-membership-settings-modify' |
  'name-service-cache-hosts-settings-get' |
  'name-service-cache-hosts-settings-modify' |
  'name-service-cache-netgroup-settings-get' |
  'name-service-cache-netgroup-settings-modify' |
  'name-service-cache-unix-group-settings-get' |
  'name-service-cache-unix-group-settings-modify' |
  'name-service-cache-unix-user-settings-get' |
  'name-service-cache-unix-user-settings-modify' |
  'name-service-nis-binding-detail-get' |
  'name-service-nis-binding-detail-get-iter' |
  'name-service-nis-show-bound' |
  'name-service-nis-show-bound-iter' |
  'name-service-unix-group-fileonly-get' |
  'name-service-unix-group-fileonly-modify' |
  'name-service-unix-user-fileonly-get' |
  'name-service-unix-user-fileonly-modify' |
  'nameservice-nsswitch-create' |
  'nameservice-nsswitch-destroy' |
  'nameservice-nsswitch-get' |
  'nameservice-nsswitch-get-iter' |
  'nameservice-nsswitch-modify' |
  'ndmp-password-generate' |
  'ndmp-vserver-attributes-get-iter' |
  'ndmp-vserver-attributes-modify' |
  'ndmp-vserver-service-disable' |
  'ndmp-vserver-service-enable' |
  'ndmp-vserver-session-info-get-iter' |
  'ndmp-vserver-session-kill' |
  'ndmp-vserver-session-kill-all' |
  'net-active-routes-get' |
  'net-active-routes-get-iter' |
  'net-arp-create' |
  'net-arp-destroy' |
  'net-arp-get' |
  'net-arp-get-iter' |
  'net-cluster-ping' |
  'net-cluster-ping6' |
  'net-ddns-get' |
  'net-ddns-get-iter' |
  'net-ddns-modify' |
  'net-dns-check-get-iter' |
  'net-dns-create' |
  'net-dns-destroy' |
  'net-dns-get' |
  'net-dns-get-iter' |
  'net-dns-modify' |
  'net-failover-group-get' |
  'net-failover-group-get-iter' |
  'net-firewall-policy-get' |
  'net-firewall-policy-get-iter' |
  'net-hosts-create' |
  'net-hosts-destroy' |
  'net-hosts-get' |
  'net-hosts-get-iter' |
  'net-hosts-modify' |
  'net-interface-get' |
  'net-interface-get-iter' |
  'net-interface-service-policy-entry-get' |
  'net-interface-service-policy-get' |
  'net-ndp-neighbor-create' |
  'net-ndp-neighbor-destroy' |
  'net-ndp-neighbor-get' |
  'net-ndp-neighbor-get-iter' |
  'net-port-get' |
  'net-port-get-iter' |
  'net-routes-create' |
  'net-routes-destroy' |
  'net-routes-get' |
  'net-routes-get-iter' |
  'net-routes-lifs-get' |
  'net-routes-lifs-get-iter' |
  'net-traceroute6' |
  'netgroups-file-delete' |
  'netgroups-file-get' |
  'netgroups-file-get-iter' |
  'nfs-disable' |
  'nfs-enable' |
  'nfs-exportfs-append-rules' |
  'nfs-exportfs-append-rules-2' |
  'nfs-exportfs-check-permission' |
  'nfs-exportfs-delete-rules' |
  'nfs-exportfs-list-rules' |
  'nfs-exportfs-list-rules-2' |
  'nfs-exportfs-modify-rule' |
  'nfs-exportfs-modify-rule-2' |
  'nfs-get-supported-sec-flavors' |
  'nfs-service-create' |
  'nfs-service-destroy' |
  'nfs-service-get' |
  'nfs-service-get-create-defaults' |
  'nfs-service-get-iter' |
  'nfs-service-modify' |
  'nfs-status' |
  'nis-create' |
  'nis-destroy' |
  'nis-get' |
  'nis-get-iter' |
  'nis-modify' |
  'nvme-create' |
  'nvme-delete' |
  'nvme-get-iter' |
  'nvme-initialize-anagrpids' |
  'nvme-interface-get-iter' |
  'nvme-modify' |
  'nvme-namespace-create' |
  'nvme-namespace-delete' |
  'nvme-namespace-get-iter' |
  'nvme-namespace-modify' |
  'nvme-namespace-resize' |
  'nvme-revert-anagrpids' |
  'nvme-subsystem-controller-get-iter' |
  'nvme-subsystem-controller-shutdown' |
  'nvme-subsystem-create' |
  'nvme-subsystem-delete' |
  'nvme-subsystem-get-iter' |
  'nvme-subsystem-host-add' |
  'nvme-subsystem-host-get-iter' |
  'nvme-subsystem-host-remove' |
  'nvme-subsystem-map-add' |
  'nvme-subsystem-map-get-iter' |
  'nvme-subsystem-map-remove' |
  'nvme-subsystem-modify' |
  'options-get' |
  'options-get-iter' |
  'options-list-info' |
  'options-modify-iter' |
  'options-set' |
  'perf-clean-stale-sample-data' |
  'perf-cleanup-sample-duration' |
  'perf-object-counter-list-info' |
  'perf-object-get-instances' |
  'perf-object-instance-list-info-iter' |
  'perf-object-list-info' |
  'perf-object-start' |
  'perf-object-stop' |
  'perf-samples-delete' |
  'perf-samples-get-iter' |
  'portset-add' |
  'portset-create' |
  'portset-destroy' |
  'portset-get-iter' |
  'portset-remove' |
  'protection-type-get-iter' |
  'qtree-create' |
  'qtree-delete' |
  'qtree-delete-async' |
  'qtree-list-iter' |
  'qtree-modify' |
  'qtree-rename' |
  'quota-add-entry' |
  'quota-delete-entry' |
  'quota-get-entry' |
  'quota-list-entries-iter' |
  'quota-modify-entry' |
  'quota-off' |
  'quota-on' |
  'quota-policy-copy' |
  'quota-policy-create' |
  'quota-policy-delete' |
  'quota-policy-delete-iter' |
  'quota-policy-get-iter' |
  'quota-policy-rename' |
  'quota-policy-rule-count-get' |
  'quota-policy-rule-count-get-iter' |
  'quota-report-iter' |
  'quota-resize' |
  'quota-set-entry' |
  'quota-status' |
  'quota-status-iter' |
  'secd-connection-timeout-get' |
  'secd-connection-timeout-get-iter' |
  'secd-connection-timeout-modify' |
  'security-certificate-ca-issued-get' |
  'security-certificate-ca-issued-get-iter' |
  'security-certificate-create' |
  'security-certificate-delete' |
  'security-certificate-delete-iter' |
  'security-certificate-generate-csr' |
  'security-certificate-get' |
  'security-certificate-get-iter' |
  'security-certificate-install' |
  'security-certificate-rename' |
  'security-certificate-revoke' |
  'security-certificate-sign' |
  'security-login-modify-password' |
  'security-login-whoami' |
  'security-ssh-add' |
  'security-ssh-get-iter' |
  'security-ssh-remove' |
  'security-ssh-reset' |
  'security-ssl-get' |
  'security-ssl-get-iter' |
  'security-ssl-modify' |
  'security-trace-filter-create' |
  'security-trace-filter-delete' |
  'security-trace-filter-get-iter' |
  'security-trace-filter-modify' |
  'security-trace-result-delete' |
  'security-trace-result-show' |
  'service-processor-api-service-disable-installed-certificates' |
  'service-processor-api-service-enable-installed-certificates' |
  'service-processor-api-service-renew-internal-certificates' |
  'sis-check' |
  'sis-disable' |
  'sis-disable-async' |
  'sis-enable' |
  'sis-enable-async' |
  'sis-get' |
  'sis-get-iter' |
  'sis-policy-create' |
  'sis-policy-delete' |
  'sis-policy-get' |
  'sis-policy-get-iter' |
  'sis-policy-modify' |
  'sis-prepare-to-downgrade' |
  'sis-promote' |
  'sis-revert-to' |
  'sis-set-config' |
  'sis-set-config-async' |
  'sis-start' |
  'sis-start-async' |
  'sis-status' |
  'sis-stop' |
  'sis-stop-async' |
  'sis-undo' |
  'snapdiff-iter-end' |
  'snapdiff-iter-next' |
  'snapdiff-iter-start' |
  'snapdiff-iter-status' |
  'snapdiff-rpc-server-create' |
  'snapdiff-rpc-server-destroy' |
  'snapdiff-rpc-server-disable' |
  'snapdiff-rpc-server-enable' |
  'snapdiff-rpc-server-get' |
  'snapdiff-rpc-server-get-create-defaults' |
  'snapdiff-rpc-server-get-iter' |
  'snapdiff-rpc-server-modify' |
  'snaplock-archive-vserver-log' |
  'snaplock-create-vserver-log' |
  'snaplock-destroy-vserver-log' |
  'snaplock-event-retention-abort' |
  'snaplock-event-retention-apply-start' |
  'snaplock-event-retention-get-iter' |
  'snaplock-event-retention-policy-create' |
  'snaplock-event-retention-policy-destroy' |
  'snaplock-event-retention-policy-get-iter' |
  'snaplock-event-retention-policy-modify' |
  'snaplock-file-privileged-delete' |
  'snaplock-get-file-retention' |
  'snaplock-get-vserver-active-log-files-iter' |
  'snaplock-get-vserver-log-iter' |
  'snaplock-legal-hold-abort' |
  'snaplock-legal-hold-begin-start' |
  'snaplock-legal-hold-dump-files-start' |
  'snaplock-legal-hold-dump-litigations-start' |
  'snaplock-legal-hold-end-start' |
  'snaplock-legal-hold-get-iter' |
  'snaplock-modify-vserver-log' |
  'snaplock-set-file-retention' |
  'snaplock-volume-set-privileged-delete' |
  'snapmirror-abort' |
  'snapmirror-abort-async' |
  'snapmirror-abort-iter' |
  'snapmirror-auto-protect-add-exclude' |
  'snapmirror-auto-protect-off' |
  'snapmirror-auto-protect-on' |
  'snapmirror-auto-protect-remove-exclude' |
  'snapmirror-break' |
  'snapmirror-break-async' |
  'snapmirror-break-iter' |
  'snapmirror-capabilities-get' |
  'snapmirror-capabilities-get-iter' |
  'snapmirror-check' |
  'snapmirror-check-iter' |
  'snapmirror-create' |
  'snapmirror-destroy' |
  'snapmirror-destroy-async' |
  'snapmirror-destroy-iter' |
  'snapmirror-get' |
  'snapmirror-get-destination' |
  'snapmirror-get-destination-iter' |
  'snapmirror-get-iter' |
  'snapmirror-history-get' |
  'snapmirror-history-get-iter' |
  'snapmirror-initialize' |
  'snapmirror-initialize-iter' |
  'snapmirror-initialize-ls-set' |
  'snapmirror-list-unprotected' |
  'snapmirror-modify' |
  'snapmirror-modify-iter' |
  'snapmirror-object-store-config-create' |
  'snapmirror-object-store-config-delete' |
  'snapmirror-object-store-config-get' |
  'snapmirror-object-store-config-get-iter' |
  'snapmirror-object-store-config-modify' |
  'snapmirror-policy-add-rule' |
  'snapmirror-policy-create' |
  'snapmirror-policy-delete' |
  'snapmirror-policy-get' |
  'snapmirror-policy-get-iter' |
  'snapmirror-policy-modify' |
  'snapmirror-policy-modify-rule' |
  'snapmirror-policy-remove-rule' |
  'snapmirror-promote' |
  'snapmirror-promote-iter' |
  'snapmirror-protect' |
  'snapmirror-quiesce' |
  'snapmirror-quiesce-iter' |
  'snapmirror-release' |
  'snapmirror-release-iter' |
  'snapmirror-restore' |
  'snapmirror-resume' |
  'snapmirror-resume-iter' |
  'snapmirror-resync' |
  'snapmirror-resync-iter' |
  'snapmirror-snapshot-owner-create' |
  'snapmirror-snapshot-owner-destroy' |
  'snapmirror-snapshot-owner-get' |
  'snapmirror-snapshot-owner-get-snapshots' |
  'snapmirror-update' |
  'snapmirror-update-iter' |
  'snapmirror-update-ls-set' |
  'snapshot-add-test-owners' |
  'snapshot-autodelete-list-info' |
  'snapshot-autodelete-set-option' |
  'snapshot-create' |
  'snapshot-create-async' |
  'snapshot-delete' |
  'snapshot-delete-async' |
  'snapshot-delta-info' |
  'snapshot-get-iter' |
  'snapshot-get-reserve' |
  'snapshot-get-schedule' |
  'snapshot-list-info' |
  'snapshot-modify-iter' |
  'snapshot-modify-snaplock-expiry-time' |
  'snapshot-multicreate' |
  'snapshot-multicreate-validate' |
  'snapshot-multidelete' |
  'snapshot-multirename' |
  'snapshot-partial-restore-file' |
  'snapshot-partial-restore-file-list-info' |
  'snapshot-policy-add-schedule' |
  'snapshot-policy-create' |
  'snapshot-policy-delete' |
  'snapshot-policy-get' |
  'snapshot-policy-get-iter' |
  'snapshot-policy-modify' |
  'snapshot-policy-modify-schedule' |
  'snapshot-policy-remove-schedule' |
  'snapshot-reclaimable-info' |
  'snapshot-remove-owner' |
  'snapshot-rename' |
  'snapshot-reserve-list-info' |
  'snapshot-restore-file' |
  'snapshot-restore-file-info' |
  'snapshot-restore-volume' |
  'snapshot-restore-volume-async' |
  'snapshot-set-reserve' |
  'snapshot-volume-info' |
  'snmp-community-add' |
  'snmp-community-delete' |
  'snmp-community-delete-all' |
  'storage-iscsi-initiator-auth-config-create' |
  'storage-iscsi-initiator-auth-config-delete' |
  'storage-iscsi-initiator-auth-config-get' |
  'storage-iscsi-initiator-auth-config-get-iter' |
  'storage-iscsi-initiator-auth-config-modify' |
  'storage-iscsi-initiator-session-create' |
  'storage-iscsi-initiator-session-delete' |
  'storage-iscsi-initiator-session-get' |
  'storage-iscsi-initiator-session-get-iter' |
  'storage-iscsi-initiator-session-modify' |
  'storage-iscsi-iswi-initiator-create' |
  'storage-iscsi-iswi-initiator-delete' |
  'storage-iscsi-iswi-initiator-get' |
  'storage-iscsi-iswi-initiator-get-iter' |
  'storage-iscsi-iswi-initiator-modify' |
  'storage-iscsi-iswi-initiator-rename' |
  'storage-service-get-iter' |
  'system-api-get-elements' |
  'system-api-list' |
  'system-api-list-types' |
  'system-get-ontapi-version' |
  'system-get-version' |
  'system-user-capability-get-iter' |
  'test-zapi-sleep' |
  'volume-autobalance-get' |
  'volume-autobalance-get-iter' |
  'volume-autobalance-start' |
  'volume-autobalance-stop' |
  'volume-autosize-get' |
  'volume-autosize-set' |
  'volume-autosize-set-async' |
  'volume-charmap-get' |
  'volume-charmap-set' |
  'volume-clone-create' |
  'volume-clone-create-async' |
  'volume-clone-get' |
  'volume-clone-get-iter' |
  'volume-clone-split-estimate' |
  'volume-clone-split-start' |
  'volume-clone-split-status' |
  'volume-clone-split-stop' |
  'volume-container' |
  'volume-create' |
  'volume-create-async' |
  'volume-destroy' |
  'volume-destroy-async' |
  'volume-encryption-conversion-get-iter' |
  'volume-encryption-conversion-pause' |
  'volume-encryption-conversion-resume' |
  'volume-encryption-conversion-start' |
  'volume-encryption-rekey-get-iter' |
  'volume-encryption-rekey-pause' |
  'volume-encryption-rekey-resume' |
  'volume-encryption-rekey-start' |
  'volume-expand-async' |
  'volume-flexgroup-capacity-tier-footprint-get-iter' |
  'volume-flexgroup-deploy-async' |
  'volume-flexgroup-deploy-simulate-aggr-layout' |
  'volume-flexgroup-get-create-limits' |
  'volume-flexgroup-get-expand-limits' |
  'volume-flexgroup-get-resize-limits' |
  'volume-footprint-get-iter' |
  'volume-get-iter' |
  'volume-get-language' |
  'volume-get-limits' |
  'volume-get-root-name' |
  'volume-get-snaplock-attrs' |
  'volume-get-volume-path' |
  'volume-modify-iter' |
  'volume-modify-iter-async' |
  'volume-mount' |
  'volume-offline' |
  'volume-offline-async' |
  'volume-online' |
  'volume-online-async' |
  'volume-options-list-info' |
  'volume-recovery-queue-get' |
  'volume-recovery-queue-get-iter' |
  'volume-recovery-queue-modify-retention' |
  'volume-recovery-queue-purge' |
  'volume-recovery-queue-recover' |
  'volume-rename' |
  'volume-rename-async' |
  'volume-restrict' |
  'volume-restrict-async' |
  'volume-set-msid' |
  'volume-set-option' |
  'volume-set-snaplock-attrs' |
  'volume-set-total-files' |
  'volume-size' |
  'volume-size-async' |
  'volume-space-get-iter' |
  'volume-storage-service-get-iter' |
  'volume-storage-service-rename' |
  'volume-unmount' |
  'vscan-active-scanner-pool-get-iter' |
  'vscan-connection-extended-stats-get-iter' |
  'vscan-connection-status-all-get-iter' |
  'vscan-events-get-iter' |
  'vscan-on-access-policy-create' |
  'vscan-on-access-policy-delete' |
  'vscan-on-access-policy-get-iter' |
  'vscan-on-access-policy-modify' |
  'vscan-on-access-policy-status-modify' |
  'vscan-on-demand-report-delete' |
  'vscan-on-demand-report-get-iter' |
  'vscan-on-demand-task-create' |
  'vscan-on-demand-task-delete' |
  'vscan-on-demand-task-get-iter' |
  'vscan-on-demand-task-modify' |
  'vscan-on-demand-task-run' |
  'vscan-reset' |
  'vscan-resolve-hostnames' |
  'vscan-scanner-pool-apply-policy' |
  'vscan-scanner-pool-create' |
  'vscan-scanner-pool-delete' |
  'vscan-scanner-pool-get-iter' |
  'vscan-scanner-pool-modify' |
  'vscan-status-get-iter' |
  'vscan-status-modify' |
  'vserver-data-policy-export' |
  'vserver-data-policy-import' |
  'vserver-data-policy-validation-get-error' |
  'vserver-get' |
  'vserver-get-iter' |
  'vserver-login-banner-get' |
  'vserver-login-banner-get-iter' |
  'vserver-login-banner-modify' |
  'vserver-login-banner-modify-iter' |
  'vserver-motd-get' |
  'vserver-motd-get-iter' |
  'vserver-motd-modify' |
  'vserver-motd-modify-iter' |
  'vserver-peer-get' |
  'vserver-peer-get-iter' |
  'vserver-peer-transition-get' |
  'vserver-peer-transition-get-iter' |
  'vserver-san-purge' |
  'vserver-san-purge-verify' |
  'vserver-saninit' |
  'vserver-show-aggr-get-iter' |
  'vvol-clone-create' |
  'vvol-create' |
  'vvol-delete' |
  'vvol-get-iter' |
  'vvol-get-op-status' |
  'vvol-mapping-create' |
  'vvol-perf-policy-modify' |
  'wafl-get-sync-status' |
  'wafl-sync';
