export interface ManagedObjectReference {
  $type: 'Alarm' |
    'AlarmManager' |
    'AuthorizationManager' |
    'CertificateManager' |
    'ClusterComputeResource' |
    'ClusterEVCManager' |
    'ClusterProfile' |
    'ClusterProfileManager' |
    'ComputeResource' |
    'ContainerView' |
    'CryptoManager' |
    'CryptoManagerHost' |
    'CryptoManagerHostKMS' |
    'CryptoManagerKmip' |
    'CustomFieldsManager' |
    'CustomizationSpecManager' |
    'Datacenter' |
    'Datastore' |
    'DatastoreNamespaceManager' |
    'DiagnosticManager' |
    'DistributedVirtualPortgroup' |
    'DistributedVirtualSwitch' |
    'DistributedVirtualSwitchManager' |
    'EnvironmentBrowser' |
    'EventHistoryCollector' |
    'EventManager' |
    'ExtensibleManagedObject' |
    'ExtensionManager' |
    'FailoverClusterConfigurator' |
    'FailoverClusterManager' |
    'FileManager' |
    'Folder' |
    'GuestAliasManager' |
    'GuestAuthManager' |
    'GuestFileManager' |
    'GuestOperationsManager' |
    'GuestProcessManager' |
    'GuestWindowsRegistryManager' |
    'HealthUpdateManager' |
    'HistoryCollector' |
    'HostAccessManager' |
    'HostActiveDirectoryAuthentication' |
    'HostAuthenticationManager' |
    'HostAuthenticationStore' |
    'HostAutoStartManager' |
    'HostBootDeviceSystem' |
    'HostCacheConfigurationManager' |
    'HostCertificateManager' |
    'HostCpuSchedulerSystem' |
    'HostDatastoreBrowser' |
    'HostDatastoreSystem' |
    'HostDateTimeSystem' |
    'HostDiagnosticSystem' |
    'HostDirectoryStore' |
    'HostEsxAgentHostManager' |
    'HostFirewallSystem' |
    'HostFirmwareSystem' |
    'HostGraphicsManager' |
    'HostHealthStatusSystem' |
    'HostImageConfigManager' |
    'HostKernelModuleSystem' |
    'HostLocalAccountManager' |
    'HostLocalAuthentication' |
    'HostMemorySystem' |
    'HostNetworkSystem' |
    'HostNvdimmSystem' |
    'HostPatchManager' |
    'HostPciPassthruSystem' |
    'HostPowerSystem' |
    'HostProfile' |
    'HostProfileManager' |
    'HostServiceSystem' |
    'HostSnmpSystem' |
    'HostSpecificationManager' |
    'HostStorageSystem' |
    'HostSystem' |
    'HostVFlashManager' |
    'HostVirtualNicManager' |
    'HostVMotionSystem' |
    'HostVsanInternalSystem' |
    'HostVsanSystem' |
    'HostVStorageObjectManager' |
    'HttpNfcLease' |
    'InventoryView' |
    'IoFilterManager' |
    'IpPoolManager' |
    'IscsiManager' |
    'LicenseAssignmentManager' |
    'LicenseManager' |
    'ListView' |
    'LocalizationManager' |
    'ManagedEntity' |
    'ManagedObjectView' |
    'MessageBusProxy' |
    'Network' |
    'OpaqueNetwork' |
    'OptionManager' |
    'OverheadMemoryManager' |
    'OvfManager' |
    'PerformanceManager' |
    'Profile' |
    'ProfileComplianceManager' |
    'ProfileManager' |
    'PropertyCollector' |
    'PropertyFilter' |
    'ResourcePlanningManager' |
    'ResourcePool' |
    'ScheduledTask' |
    'ScheduledTaskManager' |
    'SearchIndex' |
    'ServiceInstance' |
    'ServiceManager' |
    'SessionManager' |
    'SimpleCommand' |
    'StoragePod' |
    'StorageResourceManager' |
    'Task' |
    'TaskHistoryCollector' |
    'TaskManager' |
    'UserDirectory' |
    'VcenterVStorageObjectManager' |
    'View' |
    'ViewManager' |
    'VirtualApp' |
    'VirtualDiskManager' |
    'VirtualizationManager' |
    'VirtualMachine' |
    'VirtualMachineCompatibilityChecker' |
    'VirtualMachineProvisioningChecker' |
    'VirtualMachineSnapshot' |
    'VmwareDistributedVirtualSwitch' |
    'VsanUpgradeSystem' |
    'VStorageObjectManagerBase';
  _value: string;
}


