import {DynamicData} from './dynamic-data';

import {VirtualMachineConnectionState} from './virtual-machine-connection-state';
import {VirtualMachineRuntimeInfoDasProtectionState} from './virtual-machine-runtime-info-das-protection-state';
import {VirtualMachineDeviceRuntimeInfo} from './virtual-machine-device-runtime-info';
import {VirtualMachineFaultToleranceState} from './virtual-machine-fault-tolerance-state';
import {HostFeatureMask} from './host-feature-mask';
import {VirtualMachineFeatureRequirement} from './virtual-machine-feature-requirement';
import {ManagedObjectReference} from './managed-object-reference';
import {VirtualMachinePowerState} from './virtual-machine-power-state';
import {VirtualMachineQuestionInfo} from './virtual-machine-question-info';
import {VirtualMachineRecordReplayState} from './virtual-machine-record-replay-state';
import {Int} from './int';
import {DateTime} from './date-time';
import {Long} from './long';
export interface VirtualMachineRuntimeInfo extends DynamicData {
  bootTime?: DateTime;
  cleanPowerOff?: boolean;
  connectionState: VirtualMachineConnectionState;
  consolidationNeeded: boolean;
  cryptoState?: string;
  dasVmProtection?: VirtualMachineRuntimeInfoDasProtectionState;
  device?: VirtualMachineDeviceRuntimeInfo[];
  faultToleranceState: VirtualMachineFaultToleranceState;
  featureMask?: HostFeatureMask[];
  featureRequirement?: VirtualMachineFeatureRequirement[];
  host?: ManagedObjectReference & { $type: 'HostSystem' };
  instantCloneFrozen?: boolean;
  maxCpuUsage?: Int;
  maxMemoryUsage?: Int;
  memoryOverhead?: Long;
  minRequiredEVCModeKey?: string;
  needSecondaryReason?: string;
  numMksConnections: Int;
  offlineFeatureRequirement?: VirtualMachineFeatureRequirement[];
  onlineStandby: boolean;
  paused?: boolean;
  powerState: VirtualMachinePowerState;
  question?: VirtualMachineQuestionInfo;
  quiescedForkParent?: boolean;
  recordReplayState: VirtualMachineRecordReplayState;
  snapshotInBackground?: boolean;
  suspendInterval?: Long;
  suspendTime?: DateTime;
  toolsInstallerMounted: boolean;
  vFlashCacheAllocation?: Long;
}
