export type RecommendationReasonCode =
  'antiAffin' |
  'balanceDatastoreIOLoad' |
  'balanceDatastoreIOPSReservation' |
  'balanceDatastoreSpaceUsage' |
  'checkResource' |
  'datastoreMaint' |
  'datastoreSpaceOutage' |
  'enterStandby' |
  'fairnessCpuAvg' |
  'fairnessMemAvg' |
  'ftConstraints' |
  'hostExitDegradation' |
  'hostInDegradation' |
  'hostMaint' |
  'increaseCapacity' |
  'iolbDisabledInternal' |
  'jointAffin' |
  'maxVmsConstraint' |
  'networkBandwidthReservation' |
  'powerOnVm' |
  'powerSaving' |
  'reservationCpu' |
  'reservationMem' |
  'storagePlacement' |
  'unreservedCapacity' |
  'virtualDiskAntiAffin' |
  'virtualDiskJointAffin' |
  'vmHostHardAffinity' |
  'vmHostSoftAffinity' |
  'xvmotionPlacement';