export type VirtualMachineGuestOsIdentifier =
  'amazonlinux2_64Guest' |
  'asianux3_64Guest' |
  'asianux3Guest' |
  'asianux4_64Guest' |
  'asianux4Guest' |
  'asianux5_64Guest' |
  'asianux7_64Guest' |
  'asianux8_64Guest' |
  'centos6_64Guest' |
  'centos64Guest' |
  'centos6Guest' |
  'centos7_64Guest' |
  'centos7Guest' |
  'centos8_64Guest' |
  'centosGuest' |
  'coreos64Guest' |
  'darwin10_64Guest' |
  'darwin10Guest' |
  'darwin11_64Guest' |
  'darwin11Guest' |
  'darwin12_64Guest' |
  'darwin13_64Guest' |
  'darwin14_64Guest' |
  'darwin15_64Guest' |
  'darwin16_64Guest' |
  'darwin17_64Guest' |
  'darwin18_64Guest' |
  'darwin64Guest' |
  'darwinGuest' |
  'debian10_64Guest' |
  'debian10Guest' |
  'debian4_64Guest' |
  'debian4Guest' |
  'debian5_64Guest' |
  'debian5Guest' |
  'debian6_64Guest' |
  'debian6Guest' |
  'debian7_64Guest' |
  'debian7Guest' |
  'debian8_64Guest' |
  'debian8Guest' |
  'debian9_64Guest' |
  'debian9Guest' |
  'dosGuest' |
  'eComStation2Guest' |
  'eComStationGuest' |
  'fedora64Guest' |
  'fedoraGuest' |
  'freebsd11_64Guest' |
  'freebsd11Guest' |
  'freebsd12_64Guest' |
  'freebsd12Guest' |
  'freebsd64Guest' |
  'freebsdGuest' |
  'genericLinuxGuest' |
  'mandrakeGuest' |
  'mandriva64Guest' |
  'mandrivaGuest' |
  'netware4Guest' |
  'netware5Guest' |
  'netware6Guest' |
  'nld9Guest' |
  'oesGuest' |
  'openServer5Guest' |
  'openServer6Guest' |
  'opensuse64Guest' |
  'opensuseGuest' |
  'oracleLinux6_64Guest' |
  'oracleLinux64Guest' |
  'oracleLinux6Guest' |
  'oracleLinux7_64Guest' |
  'oracleLinux7Guest' |
  'oracleLinux8_64Guest' |
  'oracleLinuxGuest' |
  'os2Guest' |
  'other24xLinux64Guest' |
  'other24xLinuxGuest' |
  'other26xLinux64Guest' |
  'other26xLinuxGuest' |
  'other3xLinux64Guest' |
  'other3xLinuxGuest' |
  'other4xLinux64Guest' |
  'other4xLinuxGuest' |
  'otherGuest' |
  'otherGuest64' |
  'otherLinux64Guest' |
  'otherLinuxGuest' |
  'redhatGuest' |
  'rhel2Guest' |
  'rhel3_64Guest' |
  'rhel3Guest' |
  'rhel4_64Guest' |
  'rhel4Guest' |
  'rhel5_64Guest' |
  'rhel5Guest' |
  'rhel6_64Guest' |
  'rhel6Guest' |
  'rhel7_64Guest' |
  'rhel7Guest' |
  'rhel8_64Guest' |
  'sjdsGuest' |
  'sles10_64Guest' |
  'sles10Guest' |
  'sles11_64Guest' |
  'sles11Guest' |
  'sles12_64Guest' |
  'sles12Guest' |
  'sles15_64Guest' |
  'sles64Guest' |
  'slesGuest' |
  'solaris10_64Guest' |
  'solaris10Guest' |
  'solaris11_64Guest' |
  'solaris6Guest' |
  'solaris7Guest' |
  'solaris8Guest' |
  'solaris9Guest' |
  'suse64Guest' |
  'suseGuest' |
  'turboLinux64Guest' |
  'turboLinuxGuest' |
  'ubuntu64Guest' |
  'ubuntuGuest' |
  'unixWare7Guest' |
  'vmkernel5Guest' |
  'vmkernel65Guest' |
  'vmkernel6Guest' |
  'vmkernelGuest' |
  'vmwarePhoton64Guest' |
  'win2000AdvServGuest' |
  'win2000ProGuest' |
  'win2000ServGuest' |
  'win31Guest' |
  'win95Guest' |
  'win98Guest' |
  'windows7_64Guest' |
  'windows7Guest' |
  'windows7Server64Guest' |
  'windows8_64Guest' |
  'windows8Guest' |
  'windows8Server64Guest' |
  'windows9_64Guest' |
  'windows9Guest' |
  'windows9Server64Guest' |
  'windowsHyperVGuest' |
  'winLonghorn64Guest' |
  'winLonghornGuest' |
  'winMeGuest' |
  'winNetBusinessGuest' |
  'winNetDatacenter64Guest' |
  'winNetDatacenterGuest' |
  'winNetEnterprise64Guest' |
  'winNetEnterpriseGuest' |
  'winNetStandard64Guest' |
  'winNetStandardGuest' |
  'winNetWebGuest' |
  'winNTGuest' |
  'winVista64Guest' |
  'winVistaGuest' |
  'winXPHomeGuest' |
  'winXPPro64Guest' |
  'winXPProGuest';