export type VmFaultToleranceConfigIssueReasonForIssue =
  'cpuHvDisabled' |
  'cpuHvUnsupported' |
  'cpuHwmmuUnsupported' |
  'esxAgentVm' |
  'ftSecondaryVm' |
  'ftUnsupportedHardware' |
  'ftUnsupportedProduct' |
  'haNotEnabled' |
  'hasEFIFirmware' |
  'hasLocalDisk' |
  'hasNestedHVConfiguration' |
  'hasSnapshots' |
  'hasUnsupportedDisk' |
  'hasVFlashConfiguration' |
  'hostInactive' |
  'insufficientBandwidth' |
  'missingFTLoggingNic' |
  'missingVMotionNic' |
  'moreThanOneSecondary' |
  'multipleVCPU' |
  'noConfig' |
  'recordReplayNotSupported' |
  'replayNotSupported' |
  'templateVm' |
  'thinDisk' |
  'tooManyVCPUs' |
  'tooMuchMemory' |
  'unsupportedProduct' |
  'verifySSLCertificateFlagNotSet' |
  'video3dEnabled';