export type VmwareSdkFunctions =
   'AbandonHciWorkflow' |
   'AddHost_Task' |
   'ApplyRecommendation' |
   'CancelRecommendation' |
   'ClusterEnterMaintenanceMode' |
   'ConfigureHCI_Task' |
   'EvcManager' |
   'ExtendHCI_Task' |
   'FindRulesForVm' |
   'GetResourceUsage' |
   'MoveHostInto_Task' |
   'MoveInto_Task' |
   'PlaceVm' |
   'RecommendHostsForVm' |
   'ReconfigureCluster_Task' |
   'RefreshRecommendation' |
   'RetrieveDasAdvancedRuntimeInfo' |
   'StampAllRulesWithUuid_Task' |
   'ValidateHCIConfiguration' |
   'AbdicateDomOwnership' |
   'CanProvisionObjects' |
   'DeleteVsanObjects' |
   'GetVsanObjExtAttrs' |
   'QueryCmmds' |
   'QueryObjectsOnPhysicalVsanDisk' |
   'QueryPhysicalVsanDisks' |
   'QuerySyncingVsanObjects' |
   'QueryVsanObjects' |
   'QueryVsanObjectUuidsByFilter' |
   'QueryVsanStatistics' |
   'ReconfigurationSatisfiable' |
   'ReconfigureDomObject' |
   'RunVsanPhysicalDiskDiagnostics' |
   'UpgradeVsanObjects' |
   'AcknowledgeAlarm' |
   'AreAlarmActionsEnabled' |
   'ClearTriggeredAlarms' |
   'CreateAlarm' |
   'EnableAlarmActions' |
   'GetAlarm' |
   'GetAlarmState' |
   'AcquireCimServicesTicket' |
   'ConfigureCryptoKey' |
   'DisconnectHost_Task' |
   'EnableCrypto' |
   'EnterLockdownMode' |
   'EnterMaintenanceMode_Task' |
   'ExitLockdownMode' |
   'ExitMaintenanceMode_Task' |
   'PowerDownHostToStandBy_Task' |
   'PowerUpHostFromStandBy_Task' |
   'PrepareCrypto' |
   'QueryHostConnectionInfo' |
   'QueryMemoryOverhead' |
   'QueryMemoryOverheadEx' |
   'QueryProductLockerLocation' |
   'QueryTpmAttestationReport' |
   'RebootHost_Task' |
   'ReconfigureHostForDAS_Task' |
   'ReconnectHost_Task' |
   'RetrieveHardwareUptime' |
   'ShutdownHost_Task' |
   'UpdateFlags' |
   'UpdateIpmi' |
   'UpdateProductLockerLocation_Task' |
   'UpdateSystemResources' |
   'UpdateSystemSwapConfiguration' |
   'AcquireCloneTicket' |
   'AcquireGenericServiceTicket' |
   'AcquireLocalTicket' |
   'CloneSession' |
   'ImpersonateUser' |
   'Login' |
   'LoginBySSPI' |
   'LoginByToken' |
   'LoginExtensionByCertificate' |
   'LoginExtensionBySubjectName' |
   'Logout' |
   'SessionIsActive' |
   'SetLocale' |
   'TerminateSession' |
   'UpdateServiceMessage' |
   'AcquireCredentialsInGuest' |
   'ReleaseCredentialsInGuest' |
   'ValidateCredentialsInGuest' |
   'AcquireMksTicket' |
   'AcquireTicket' |
   'AnswerVM' |
   'ApplyEvcModeVM_Task' |
   'AttachDisk_Task' |
   'CheckCustomizationSpec' |
   'CloneVM_Task' |
   'ConsolidateVMDisks_Task' |
   'CreateScreenshot_Task' |
   'CreateSecondaryVM_Task' |
   'CreateSecondaryVMEx_Task' |
   'CreateSnapshot_Task' |
   'CreateSnapshotEx_Task' |
   'CryptoUnlock_Task' |
   'CustomizeVM_Task' |
   'DefragmentAllDisks' |
   'DetachDisk_Task' |
   'DisableSecondaryVM_Task' |
   'EnableSecondaryVM_Task' |
   'EstimateStorageForConsolidateSnapshots_Task' |
   'ExportVm' |
   'ExtractOvfEnvironment' |
   'InstantClone_Task' |
   'MakePrimaryVM_Task' |
   'MarkAsTemplate' |
   'MarkAsVirtualMachine' |
   'MigrateVM_Task' |
   'MountToolsInstaller' |
   'PowerOffVM_Task' |
   'PowerOnVM_Task' |
   'PromoteDisks_Task' |
   'PutUsbScanCodes' |
   'QueryChangedDiskAreas' |
   'QueryFaultToleranceCompatibility' |
   'QueryFaultToleranceCompatibilityEx' |
   'QueryUnownedFiles' |
   'RebootGuest' |
   'ReconfigVM_Task' |
   'RefreshStorageInfo' |
   'reloadVirtualMachineFromPath_Task' |
   'RelocateVM_Task' |
   'RemoveAllSnapshots_Task' |
   'ResetGuestInformation' |
   'ResetVM_Task' |
   'RevertToCurrentSnapshot_Task' |
   'SendNMI' |
   'SetDisplayTopology' |
   'SetScreenResolution' |
   'ShutdownGuest' |
   'StandbyGuest' |
   'StartRecording_Task' |
   'StartReplaying_Task' |
   'StopRecording_Task' |
   'StopReplaying_Task' |
   'SuspendVM_Task' |
   'TerminateFaultTolerantVM_Task' |
   'TerminateVM' |
   'TurnOffFaultToleranceForVM_Task' |
   'UnmountToolsInstaller' |
   'UnregisterVM' |
   'UpgradeTools_Task' |
   'UpgradeVM_Task' |
   'AddAuthorizationRole' |
   'FetchUserPrivilegeOnEntities' |
   'HasPrivilegeOnEntities' |
   'HasPrivilegeOnEntity' |
   'HasUserPrivilegeOnEntities' |
   'MergePermissions' |
   'RemoveAuthorizationRole' |
   'RemoveEntityPermission' |
   'ResetEntityPermissions' |
   'RetrieveAllPermissions' |
   'RetrieveEntityPermissions' |
   'RetrieveRolePermissions' |
   'SetEntityPermissions' |
   'UpdateAuthorizationRole' |
   'AddCustomFieldDef' |
   'RemoveCustomFieldDef' |
   'RenameCustomFieldDef' |
   'SetField' |
   'AddDisks_Task' |
   'EvacuateVsanNode_Task' |
   'InitializeDisks_Task' |
   'QueryDisksForVsan' |
   'QueryHostStatus' |
   'RecommissionVsanNode_Task' |
   'RemoveDisk_Task' |
   'RemoveDiskMapping_Task' |
   'UnmountDiskMapping_Task' |
   'UpdateVsan_Task' |
   'AddDVPortgroup_Task' |
   'AddNetworkResourcePool' |
   'CreateDVPortgroup_Task' |
   'DvsReconfigureVmVnicNetworkResourcePool_Task' |
   'DVSRollback_Task' |
   'EnableNetworkResourceManagement' |
   'FetchDVPortKeys' |
   'FetchDVPorts' |
   'LookupDvPortGroup' |
   'MergeDvs_Task' |
   'MoveDVPort_Task' |
   'PerformDvsProductSpecOperation_Task' |
   'QueryUsedVlanIdInDvs' |
   'ReconfigureDVPort_Task' |
   'ReconfigureDvs_Task' |
   'RectifyDvsHost_Task' |
   'RefreshDVPortState' |
   'RemoveNetworkResourcePool' |
   'UpdateDvsCapability' |
   'UpdateDVSHealthCheckConfig_Task' |
   'UpdateNetworkResourcePool' |
   'AddFilter' |
   'AddFilterEntities' |
   'AddMonitoredEntities' |
   'HasMonitoredEntity' |
   'HasProvider' |
   'PostHealthUpdates' |
   'QueryFilterEntities' |
   'QueryFilterInfoIds' |
   'QueryFilterList' |
   'QueryFilterName' |
   'QueryHealthUpdateInfos' |
   'QueryHealthUpdates' |
   'QueryMonitoredEntities' |
   'QueryProviderList' |
   'QueryProviderName' |
   'QueryUnmonitoredHosts' |
   'RegisterHealthUpdateProvider' |
   'RemoveFilter' |
   'RemoveFilterEntities' |
   'RemoveMonitoredEntities' |
   'UnregisterHealthUpdateProvider' |
   'AddGuestAlias' |
   'ListGuestAliases' |
   'ListGuestMappedAliases' |
   'RemoveGuestAlias' |
   'RemoveGuestAliasByCert' |
   'AddInternetScsiSendTargets' |
   'AddInternetScsiStaticTargets' |
   'AttachScsiLun' |
   'AttachScsiLunEx_Task' |
   'AttachVmfsExtent' |
   'ChangeNFSUserPassword' |
   'ClearNFSUser' |
   'ComputeDiskPartitionInfo' |
   'ComputeDiskPartitionInfoForResize' |
   'DeleteScsiLunState' |
   'DeleteVffsVolumeState' |
   'DeleteVmfsVolumeState' |
   'DestroyVffs' |
   'DetachScsiLun' |
   'DetachScsiLunEx_Task' |
   'DisableMultipathPath' |
   'DiscoverFcoeHbas' |
   'EnableMultipathPath' |
   'ExpandVmfsExtent' |
   'ExtendVffs' |
   'FormatVffs' |
   'FormatVmfs' |
   'MarkAsLocal_Task' |
   'MarkAsNonLocal_Task' |
   'MarkAsNonSsd_Task' |
   'MarkAsSsd_Task' |
   'MarkForRemoval' |
   'MarkPerenniallyReserved' |
   'MarkPerenniallyReservedEx_Task' |
   'MountVffsVolume' |
   'MountVmfsVolume' |
   'MountVmfsVolumeEx_Task' |
   'QueryAvailableSsds' |
   'QueryNFSUser' |
   'QueryPathSelectionPolicyOptions' |
   'QueryStorageArrayTypePolicyOptions' |
   'QueryUnresolvedVmfsVolume' |
   'QueryVmfsConfigOption' |
   'RefreshStorageSystem' |
   'RemoveInternetScsiSendTargets' |
   'RemoveInternetScsiStaticTargets' |
   'RescanAllHba' |
   'RescanHba' |
   'RescanVffs' |
   'RescanVmfs' |
   'ResolveMultipleUnresolvedVmfsVolumes' |
   'ResolveMultipleUnresolvedVmfsVolumesEx_Task' |
   'RetrieveDiskPartitionInfo' |
   'SetMultipathLunPolicy' |
   'SetNFSUser' |
   'TurnDiskLocatorLedOff_Task' |
   'TurnDiskLocatorLedOn_Task' |
   'UnmapVmfsVolumeEx_Task' |
   'UnmountForceMountedVmfsVolume' |
   'UnmountVffsVolume' |
   'UnmountVmfsVolume' |
   'UnmountVmfsVolumeEx_Task' |
   'UpdateDiskPartitions' |
   'UpdateInternetScsiAdvancedOptions' |
   'UpdateInternetScsiAlias' |
   'UpdateInternetScsiAuthenticationProperties' |
   'UpdateInternetScsiDigestProperties' |
   'UpdateInternetScsiDiscoveryProperties' |
   'UpdateInternetScsiIPProperties' |
   'UpdateInternetScsiName' |
   'UpdateScsiLunDisplayName' |
   'UpdateSoftwareInternetScsiEnabled' |
   'UpdateVmfsUnmapBandwidth' |
   'UpdateVmfsUnmapPriority' |
   'UpgradeVmfs' |
   'UpgradeVmLayout' |
   'AddKey' |
   'AddKeys' |
   'ListKeys' |
   'RemoveKey' |
   'RemoveKeys' |
   'AddLicense' |
   'CheckLicenseFeature' |
   'ConfigureLicenseSource' |
   'DecodeLicense' |
   'DisableFeature' |
   'EnableFeature' |
   'QueryLicenseSourceAvailability' |
   'QueryLicenseUsage' |
   'QuerySupportedFeatures' |
   'RemoveLicense' |
   'RemoveLicenseLabel' |
   'SetLicenseEdition' |
   'UpdateLicense' |
   'UpdateLicenseLabel' |
   'AddPortGroup' |
   'AddServiceConsoleVirtualNic' |
   'AddVirtualNic' |
   'AddVirtualSwitch' |
   'QueryNetworkHint' |
   'RefreshNetworkSystem' |
   'RemovePortGroup' |
   'RemoveServiceConsoleVirtualNic' |
   'RemoveVirtualNic' |
   'RemoveVirtualSwitch' |
   'RestartServiceConsoleVirtualNic' |
   'UpdateConsoleIpRouteConfig' |
   'UpdateDnsConfig' |
   'UpdateIpRouteConfig' |
   'UpdateIpRouteTableConfig' |
   'UpdateNetworkConfig' |
   'UpdatePhysicalNicLinkSpeed' |
   'UpdatePortGroup' |
   'UpdateServiceConsoleVirtualNic' |
   'UpdateVirtualNic' |
   'UpdateVirtualSwitch' |
   'AddStandaloneHost_Task' |
   'BatchAddHostsToCluster_Task' |
   'BatchAddStandaloneHosts_Task' |
   'CreateCluster' |
   'CreateClusterEx' |
   'CreateDatacenter' |
   'CreateDVS_Task' |
   'CreateFolder' |
   'CreateStoragePod' |
   'CreateVM_Task' |
   'MoveIntoFolder_Task' |
   'RegisterVM_Task' |
   'UnregisterAndDestroy_Task' |
   'AllocateIpv4Address' |
   'AllocateIpv6Address' |
   'CreateIpPool' |
   'DestroyIpPool' |
   'QueryIPAllocations' |
   'QueryIpPools' |
   'ReleaseIpAllocation' |
   'UpdateIpPool' |
   'ApplyEntitiesConfig_Task' |
   'ApplyHostConfig_Task' |
   'CheckAnswerFileStatus_Task' |
   'CompositeHostProfile_Task' |
   'CreateDefaultProfile' |
   'ExportAnswerFile_Task' |
   'GenerateConfigTaskList' |
   'GenerateHostConfigTaskSpec_Task' |
   'GenerateHostProfileTaskList_Task' |
   'QueryAnswerFileStatus' |
   'QueryHostProfileMetadata' |
   'QueryProfileStructure' |
   'RetrieveAnswerFile' |
   'RetrieveAnswerFileForProfile' |
   'RetrieveHostCustomizations' |
   'RetrieveHostCustomizationsForProfile' |
   'UpdateAnswerFile_Task' |
   'UpdateHostCustomizations_Task' |
   'ValidateHostProfileComposition_Task' |
   'ApplyStorageDrsRecommendation_Task' |
   'ApplyStorageDrsRecommendationToPod_Task' |
   'CancelStorageDrsRecommendation' |
   'ConfigureDatastoreIORM_Task' |
   'ConfigureStorageDrsForPod_Task' |
   'QueryDatastorePerformanceSummary' |
   'QueryIORMConfigOption' |
   'RecommendDatastores' |
   'RefreshStorageDrsRecommendation' |
   'RefreshStorageDrsRecommendationsForPod_Task' |
   'ValidateStoragePodConfig' |
   'AssignUserToGroup' |
   'ChangePassword' |
   'CreateGroup' |
   'CreateUser' |
   'RemoveGroup' |
   'RemoveUser' |
   'UnassignUserFromGroup' |
   'UpdateUser' |
   'AssociateProfile' |
   'CheckProfileCompliance_Task' |
   'DestroyProfile' |
   'DissociateProfile' |
   'ExportProfile' |
   'RetrieveDescription' |
   'AttachTagToVStorageObject' |
   'ClearVStorageObjectControlFlags' |
   'CloneVStorageObject_Task' |
   'CreateDisk_Task' |
   'CreateDiskFromSnapshot_Task' |
   'DeleteSnapshot_Task' |
   'DeleteVStorageObject_Task' |
   'DetachTagFromVStorageObject' |
   'ExtendDisk_Task' |
   'InflateDisk_Task' |
   'ListTagsAttachedToVStorageObject' |
   'ListVStorageObject' |
   'ListVStorageObjectsAttachedToTag' |
   'ReconcileDatastoreInventory_Task' |
   'RegisterDisk' |
   'RelocateVStorageObject_Task' |
   'RenameVStorageObject' |
   'RetrieveSnapshotInfo' |
   'RetrieveVStorageInfrastructureObjectPolicy' |
   'RetrieveVStorageObject' |
   'RetrieveVStorageObjectAssociations' |
   'RetrieveVStorageObjectState' |
   'RevertVStorageObject_Task' |
   'ScheduleReconcileDatastoreInventory' |
   'SetVStorageObjectControlFlags' |
   'UpdateVStorageInfrastructureObjectPolicy_Task' |
   'UpdateVStorageObjectPolicy_Task' |
   'VStorageObjectCreateSnapshot_Task' |
   'AutoStartPowerOff' |
   'AutoStartPowerOn' |
   'ReconfigureAutostart' |
   'BackupFirmwareConfiguration' |
   'QueryFirmwareConfigUploadURL' |
   'ResetFirmwareToFactoryDefaults' |
   'RestoreFirmwareConfiguration' |
   'BatchQueryConnectInfo' |
   'PowerOnMultiVM_Task' |
   'QueryConnectionInfo' |
   'QueryConnectionInfoViaSpec' |
   'queryDatacenterConfigOptionDescriptor' |
   'ReconfigureDatacenter_Task' |
   'BindVnic' |
   'QueryBoundVnics' |
   'QueryCandidateNics' |
   'QueryMigrationDependencies' |
   'QueryPnicStatus' |
   'QueryVnicStatus' |
   'UnbindVnic' |
   'BrowseDiagnosticLog' |
   'GenerateLogBundles_Task' |
   'QueryDescriptions' |
   'CancelRetrievePropertiesEx' |
   'CancelWaitForUpdates' |
   'CheckForUpdates' |
   'ContinueRetrievePropertiesEx' |
   'CreateFilter' |
   'CreatePropertyCollector' |
   'DestroyPropertyCollector' |
   'RetrieveProperties' |
   'RetrievePropertiesEx' |
   'WaitForUpdates' |
   'WaitForUpdatesEx' |
   'CancelTask' |
   'SetTaskDescription' |
   'SetTaskState' |
   'UpdateProgress' |
   'CertMgrRefreshCACertificatesAndCRLs_Task' |
   'CertMgrRefreshCertificates_Task' |
   'CertMgrRevokeCertificates_Task' |
   'ChangeAccessMode' |
   'ChangeLockdownMode' |
   'QueryLockdownExceptions' |
   'QuerySystemUsers' |
   'RetrieveHostAccessControlEntries' |
   'UpdateLockdownExceptions' |
   'UpdateSystemUsers' |
   'ChangeFileAttributesInGuest' |
   'CreateTemporaryDirectoryInGuest' |
   'CreateTemporaryFileInGuest' |
   'DeleteDirectoryInGuest' |
   'DeleteFileInGuest' |
   'InitiateFileTransferFromGuest' |
   'InitiateFileTransferToGuest' |
   'ListFilesInGuest' |
   'MakeDirectoryInGuest' |
   'MoveDirectoryInGuest' |
   'MoveFileInGuest' |
   'ChangeKey_Task' |
   'CryptoManagerHostEnable' |
   'CryptoManagerHostPrepare' |
   'ChangeOwner' |
   'CopyDatastoreFile_Task' |
   'DeleteDatastoreFile_Task' |
   'MakeDirectory' |
   'MoveDatastoreFile_Task' |
   'CheckAddHostEvc_Task' |
   'CheckConfigureEvcMode_Task' |
   'ConfigureEvcMode_Task' |
   'DisableEvcMode_Task' |
   'CheckClone_Task' |
   'CheckInstantClone_Task' |
   'CheckMigrate_Task' |
   'CheckRelocate_Task' |
   'QueryVMotionCompatibilityEx_Task' |
   'CheckCompatibility_Task' |
   'CheckPowerOn_Task' |
   'CheckVmConfig_Task' |
   'CheckCompliance_Task' |
   'ClearComplianceStatus' |
   'QueryComplianceStatus' |
   'QueryExpressionMetadata' |
   'CheckCustomizationResources' |
   'CreateCustomizationSpec' |
   'CustomizationSpecItemToXml' |
   'DeleteCustomizationSpec' |
   'DoesCustomizationSpecExist' |
   'DuplicateCustomizationSpec' |
   'GetCustomizationSpec' |
   'OverwriteCustomizationSpec' |
   'RenameCustomizationSpec' |
   'XmlToCustomizationSpecItem' |
   'CheckHostPatch_Task' |
   'InstallHostPatch_Task' |
   'InstallHostPatchV2_Task' |
   'QueryHostPatch_Task' |
   'ScanHostPatch_Task' |
   'ScanHostPatchV2_Task' |
   'StageHostPatch_Task' |
   'UninstallHostPatch_Task' |
   'ClearSystemEventLog' |
   'FetchSystemEventLog' |
   'RefreshHealthStatusSystem' |
   'ResetSystemHealthInfo' |
   'CloneVApp_Task' |
   'ExportVApp' |
   'PowerOffVApp_Task' |
   'PowerOnVApp_Task' |
   'SuspendVApp_Task' |
   'unregisterVApp_Task' |
   'UpdateLinkedChildren' |
   'UpdateVAppConfig' |
   'CloseInventoryViewFolder' |
   'OpenInventoryViewFolder' |
   'ConfigureDatastorePrincipal' |
   'CreateLocalDatastore' |
   'CreateNasDatastore' |
   'CreateVmfsDatastore' |
   'CreateVvolDatastore' |
   'ExpandVmfsDatastore' |
   'ExtendVmfsDatastore' |
   'QueryAvailableDisksForVmfs' |
   'QueryUnresolvedVmfsVolumes' |
   'QueryVmfsDatastoreCreateOptions' |
   'QueryVmfsDatastoreExpandOptions' |
   'QueryVmfsDatastoreExtendOptions' |
   'RemoveDatastore' |
   'RemoveDatastoreEx_Task' |
   'ResignatureUnresolvedVmfsVolume_Task' |
   'UpdateLocalSwapDatastore' |
   'ConfigureHostCache_Task' |
   'ConfigurePowerPolicy' |
   'configureVcha_Task' |
   'createPassiveNode_Task' |
   'createWitnessNode_Task' |
   'deployVcha_Task' |
   'destroyVcha_Task' |
   'getVchaConfig' |
   'prepareVcha_Task' |
   'ConfigureVFlashResourceEx_Task' |
   'HostConfigureVFlashResource' |
   'HostConfigVFlashCache' |
   'HostGetVFlashModuleDefaultConfig' |
   'HostRemoveVFlashResource' |
   'ConvertNamespacePathToUuidPath' |
   'CreateDirectory' |
   'DeleteDirectory' |
   'CopyVirtualDisk_Task' |
   'CreateVirtualDisk_Task' |
   'DefragmentVirtualDisk_Task' |
   'DeleteVirtualDisk_Task' |
   'EagerZeroVirtualDisk_Task' |
   'ExtendVirtualDisk_Task' |
   'ImportUnmanagedSnapshot' |
   'InflateVirtualDisk_Task' |
   'MoveVirtualDisk_Task' |
   'QueryVirtualDiskFragmentation' |
   'QueryVirtualDiskGeometry' |
   'QueryVirtualDiskUuid' |
   'ReleaseManagedSnapshot' |
   'SetVirtualDiskUuid' |
   'ShrinkVirtualDisk_Task' |
   'ZeroFillVirtualDisk_Task' |
   'CreateChildVM_Task' |
   'CreateResourcePool' |
   'CreateVApp' |
   'DestroyChildren' |
   'ImportVApp' |
   'MoveIntoResourcePool' |
   'QueryResourceConfigOption' |
   'RefreshRuntime' |
   'RegisterChildVM_Task' |
   'UpdateChildResourceConfiguration' |
   'UpdateConfig' |
   'CreateCollectorForEvents' |
   'LogUserEvent' |
   'PostEvent' |
   'QueryEvents' |
   'RetrieveArgumentDescription' |
   'CreateCollectorForTasks' |
   'CreateTask' |
   'CreateContainerView' |
   'CreateInventoryView' |
   'CreateListView' |
   'CreateListViewFromView' |
   'CreateDescriptor' |
   'CreateImportSpec' |
   'ParseDescriptor' |
   'ValidateHost' |
   'CreateDiagnosticPartition' |
   'QueryAvailablePartition' |
   'QueryPartitionCreateDesc' |
   'QueryPartitionCreateOptions' |
   'SelectActivePartition' |
   'CreateNvdimmNamespace_Task' |
   'CreateNvdimmPMemNamespace_Task' |
   'DeleteNvdimmBlockNamespaces_Task' |
   'DeleteNvdimmNamespace_Task' |
   'CreateObjectScheduledTask' |
   'CreateScheduledTask' |
   'RetrieveEntityScheduledTask' |
   'RetrieveObjectScheduledTask' |
   'CreatePerfInterval' |
   'QueryAvailablePerfMetric' |
   'QueryPerf' |
   'QueryPerfComposite' |
   'QueryPerfCounter' |
   'QueryPerfCounterByLevel' |
   'QueryPerfProviderSummary' |
   'RemovePerfInterval' |
   'ResetCounterLevelMapping' |
   'UpdateCounterLevelMapping' |
   'UpdatePerfInterval' |
   'CreateProfile' |
   'FindAssociatedProfile' |
   'QueryPolicyMetadata' |
   'CreateRegistryKeyInGuest' |
   'DeleteRegistryKeyInGuest' |
   'DeleteRegistryValueInGuest' |
   'ListRegistryKeysInGuest' |
   'ListRegistryValuesInGuest' |
   'SetRegistryValueInGuest' |
   'CurrentTime' |
   'QueryVMotionCompatibility' |
   'RetrieveProductComponents' |
   'RetrieveServiceContent' |
   'ValidateMigration' |
   'DatastoreEnterMaintenanceMode' |
   'DatastoreExitMaintenanceMode_Task' |
   'DestroyDatastore' |
   'RefreshDatastore' |
   'RefreshDatastoreStorageInfo' |
   'RenameDatastore' |
   'UpdateVirtualMachineFiles_Task' |
   'UpdateVVolVirtualMachineFiles_Task' |
   'DeleteFile' |
   'SearchDatastore_Task' |
   'SearchDatastoreSubFolders_Task' |
   'DeleteHostSpecification' |
   'DeleteHostSubSpecification' |
   'HostSpecGetUpdatedHosts' |
   'RetrieveHostSpecification' |
   'UpdateHostSpecification' |
   'UpdateHostSubSpecification' |
   'DeselectVnic' |
   'SelectVnic' |
   'UpdateIpConfig' |
   'DeselectVnicForNicType' |
   'QueryNetConfig' |
   'SelectVnicForNicType' |
   'Destroy_Task' |
   'Reload' |
   'Rename_Task' |
   'DestroyCollector' |
   'ResetCollector' |
   'RewindCollector' |
   'SetCollectorPageSize' |
   'DestroyNetwork' |
   'DestroyPropertyFilter' |
   'DestroyView' |
   'DisableHyperThreading' |
   'EnableHyperThreading' |
   'DisableRuleset' |
   'EnableRuleset' |
   'RefreshFirewall' |
   'UpdateDefaultPolicy' |
   'UpdateRuleset' |
   'DisableSmartCardAuthentication' |
   'EnableSmartCardAuthentication' |
   'ImportCertificateForCAM_Task' |
   'InstallSmartCardTrustAnchor' |
   'JoinDomain_Task' |
   'JoinDomainWithCAM_Task' |
   'LeaveCurrentDomain_Task' |
   'ListSmartCardTrustAnchors' |
   'RemoveSmartCardTrustAnchor' |
   'RemoveSmartCardTrustAnchorByFingerprint' |
   'ReplaceSmartCardTrustAnchors' |
   'DVPortgroupRollback_Task' |
   'ReconfigureDVPortgroup_Task' |
   'DVSManagerExportEntity_Task' |
   'DVSManagerImportEntity_Task' |
   'DVSManagerLookupDvPortGroup' |
   'QueryAvailableDvsSpec' |
   'QueryCompatibleHostForExistingDvs' |
   'QueryCompatibleHostForNewDvs' |
   'QueryDvsByUuid' |
   'QueryDvsCheckCompatibility' |
   'QueryDvsCompatibleHostSpec' |
   'QueryDvsConfigTarget' |
   'QueryDvsFeatureCapability' |
   'RectifyDvsOnHost_Task' |
   'EstimateDatabaseSize' |
   'EsxAgentHostManagerUpdateConfig' |
   'ExecuteHostProfile' |
   'HostProfileResetValidationState' |
   'UpdateHostProfile' |
   'UpdateReferenceHost' |
   'ExecuteSimpleCommand' |
   'ExportSnapshot' |
   'RemoveSnapshot_Task' |
   'RenameSnapshot' |
   'RevertToSnapshot_Task' |
   'fetchSoftwarePackages' |
   'HostImageConfigGetAcceptance' |
   'HostImageConfigGetProfile' |
   'installDate' |
   'UpdateHostImageAcceptanceLevel' |
   'FindAllByDnsName' |
   'FindAllByIp' |
   'FindAllByUuid' |
   'FindByDatastorePath' |
   'FindByDnsName' |
   'FindByInventoryPath' |
   'FindByIp' |
   'FindByUuid' |
   'FindChild' |
   'FindExtension' |
   'GetPublicKey' |
   'QueryExtensionIpAllocationUsage' |
   'QueryManagedBy' |
   'RegisterExtension' |
   'SetExtensionCertificate' |
   'SetPublicKey' |
   'UnregisterExtension' |
   'UpdateExtension' |
   'GenerateCertificateSigningRequest' |
   'GenerateCertificateSigningRequestByDn' |
   'InstallServerCertificate' |
   'ListCACertificateRevocationLists' |
   'ListCACertificates' |
   'ReplaceCACertificatesAndCRLs' |
   'GenerateClientCsr' |
   'GenerateKey' |
   'GenerateSelfSignedClientCert' |
   'ListKmipServers' |
   'MarkDefault' |
   'QueryCryptoKeyStatus' |
   'RegisterKmipServer' |
   'RemoveKmipServer' |
   'RetrieveClientCert' |
   'RetrieveClientCsr' |
   'RetrieveKmipServerCert' |
   'RetrieveKmipServersStatus_Task' |
   'RetrieveSelfSignedClientCert' |
   'UpdateKmipServer' |
   'UpdateKmsSignedCsrClientCert' |
   'UpdateSelfSignedClientCert' |
   'UploadClientCert' |
   'UploadKmipServerCert' |
   'getClusterMode' |
   'GetVchaClusterHealth' |
   'initiateFailover_Task' |
   'setClusterMode_Task' |
   'HostClearVStorageObjectControlFlags' |
   'HostCloneVStorageObject_Task' |
   'HostCreateDisk_Task' |
   'HostDeleteVStorageObject_Task' |
   'HostExtendDisk_Task' |
   'HostInflateDisk_Task' |
   'HostListVStorageObject' |
   'HostReconcileDatastoreInventory_Task' |
   'HostRegisterDisk' |
   'HostRelocateVStorageObject_Task' |
   'HostRenameVStorageObject' |
   'HostRetrieveVStorageInfrastructureObjectPolicy' |
   'HostRetrieveVStorageObject' |
   'HostRetrieveVStorageObjectMetadata' |
   'HostRetrieveVStorageObjectMetadataValue' |
   'HostRetrieveVStorageObjectState' |
   'HostScheduleReconcileDatastoreInventory' |
   'HostSetVStorageObjectControlFlags' |
   'HostUpdateVStorageObjectMetadata_Task' |
   'HostVStorageObjectCreateDiskFromSnapshot_Task' |
   'HostVStorageObjectCreateSnapshot_Task' |
   'HostVStorageObjectDeleteSnapshot_Task' |
   'HostVStorageObjectRetrieveSnapshotInfo' |
   'HostVStorageObjectRevert_Task' |
   'HttpNfcLeaseAbort' |
   'HttpNfcLeaseComplete' |
   'HttpNfcLeaseGetManifest' |
   'HttpNfcLeaseProgress' |
   'HttpNfcLeasePullFromUrls_Task' |
   'HttpNfcLeaseSetManifestChecksumType' |
   'InstallIoFilter_Task' |
   'QueryDisksUsingFilter' |
   'QueryIoFilterInfo' |
   'QueryIoFilterIssues' |
   'ResolveInstallationErrorsOnCluster_Task' |
   'ResolveInstallationErrorsOnHost_Task' |
   'UninstallIoFilter_Task' |
   'UpgradeIoFilter_Task' |
   'IsSharedGraphicsActive' |
   'RefreshGraphicsManager' |
   'UpdateGraphicsConfig' |
   'ListProcessesInGuest' |
   'ReadEnvironmentVariableInGuest' |
   'StartProgramInGuest' |
   'TerminateProcessInGuest' |
   'LookupVmOverheadMemory' |
   'ModifyListView' |
   'ResetListView' |
   'ResetListViewFromView' |
   'PerformVsanUpgrade_Task' |
   'PerformVsanUpgradePreflightCheck' |
   'QueryVsanUpgradeStatus' |
   'QueryAssignedLicenses' |
   'RemoveAssignedLicense' |
   'UpdateAssignedLicense' |
   'QueryAvailableTimeZones' |
   'QueryDateTime' |
   'RefreshDateTimeSystem' |
   'UpdateDateTime' |
   'UpdateDateTimeConfig' |
   'QueryBootDevices' |
   'UpdateBootDevice' |
   'QueryConfigOption' |
   'QueryConfigOptionDescriptor' |
   'QueryConfigOptionEx' |
   'QueryConfigTarget' |
   'QueryTargetCapabilities' |
   'QueryConfiguredModuleOptionString' |
   'QueryModules' |
   'UpdateModuleOptionString' |
   'QueryHostsWithAttachedLun' |
   'QueryOptions' |
   'UpdateOptions' |
   'QueryServiceList' |
   'ReadNextEvents' |
   'ReadPreviousEvents' |
   'ReadNextTasks' |
   'ReadPreviousTasks' |
   'ReconfigureAlarm' |
   'RemoveAlarm' |
   'ReconfigureComputeResource_Task' |
   'ReconfigureScheduledTask' |
   'RemoveScheduledTask' |
   'RunScheduledTask' |
   'ReconfigureServiceConsoleReservation' |
   'ReconfigureVirtualMachineReservation' |
   'ReconfigureSnmpAgent' |
   'SendTestNotification' |
   'Refresh' |
   'UpdatePassthruConfig' |
   'RefreshServices' |
   'RestartService' |
   'StartService' |
   'StopService' |
   'UninstallService' |
   'UpdateServicePolicy' |
   'RetrieveUserGroups' |
   'setCustomValue' |
   'UpdateClusterProfile' |
   'UpdateDVSLacpGroupConfig_Task';